// This file is generated by machine-bridge/src/type-generator/generate-machine-types.ts
// Output location defaults to machine-bridge/type-detection/types.ts.
// Do not edit by hand; rerun the generator against a live OPC UA server.

export const machineTypeSource = {
    "controllerName": "CODESYS Control for Linux SL",
    "endpoint": "opc.tcp://127.0.0.1:4840",
    "generatedAt": "2026-05-18T02:06:37.670Z",
    "rootNodeId": "ns=4;s=|var|CODESYS Control for Linux SL.Application.Machine",
    "rootTag": "Machine"
} as const;

export enum CellTypes {
    UNKNOWN = 0,
    APOLLO_00251_TUBELINER = 101,
    APOLLO_00225_SAW = 102,
}
export enum SoftwareModes {
    DEV = 0,
    PRODUCTION = 1,
}
export interface MachineCfg {
    AllowAnonymousControl: boolean;
    ApiOpcuaDeviceId: number;
    CellType: CellTypes;
    DeviceIsBypassed: Array<boolean>;
    EthernetAdapterList: Array<number>;
    FirmwareVersion: string;
    MachineId: string;
    NumRegisteredDevices: number;
    SoftwareMode: SoftwareModes;
}
export interface DebugLogData {
    Id: number;
    Msg: string;
    TimeStamp: bigint | number;
}
export interface DeviceLogData {
    LastIndex: number;
    List: Array<DebugLogData>;
}
export enum Colors {
    BLACK = 0,
    RED = 1,
    ORANGE = 2,
    YELLOW = 3,
    GREEN = 4,
    BLUE = 5,
    INDIGO = 6,
    VIOLET = 7,
    GRAY = 8,
    WHITE = 9,
    LIGHTBLACK = 10,
    LIGHTRED = 11,
    LIGHTORANGE = 12,
    LIGHTYELLOW = 13,
    LIGHTGREEN = 14,
    LIGHTBLUE = 15,
    LIGHTINDIGO = 16,
    LIGHTVIOLET = 17,
    LIGHTGRAY = 18,
    LIGHTWHITE = 19,
    DARKRED = 201,
    DARKYELLOW = 203,
    DARKGRAY = 208,
    OPAQUEWHITE = 309,
    LIGHT = 1001,
    DARK = 1002,
    ACTIONBTN1 = 21,
    ACTIONBTN2 = 22,
    ACTIONBTN3 = 23,
    ACTIONBTN4 = 24,
    ACTIONBTN5 = 25,
    ACTIONBTN6 = 26,
    GOOD = 31,
    WARN = 32,
    ERROR = 33,
    KILLED = 40,
    INACTIVE = 41,
    RESETTING = 42,
    IDLE = 43,
    RUNNING = 44,
    DONE = 45,
    ABORTING = 46,
    MANUAL = 47,
    PAUSED = 48,
    FAULTED = 49,
    STOPPING = 440,
    TASKDONE = 50,
    TASKACTIVE = 51,
    TASKFUTURE = 52,
    FANUCYELLOW = 60,
    EMPTY = 100,
    PROCESSING = 101,
    RAW = 102,
    DEBURRED = 103,
    MACHINED = 104,
    WASHED = 105,
    DRYED = 106,
    SCRAPPED = 109,
    FINISHED = 110,
    DEBURRBOTTOMFINSHED = 111,
    NEXTPART = 115,
    DELETE = 116,
}
export enum ActionButtonDependencies {
    NONE = 0,
    IDLE = 1,
    IDLE_OR_INACTIVE = 2,
    ALWAYS_VISIBLE = 3,
}
export interface ActionButton {
    Color: Colors;
    Dependency: ActionButtonDependencies;
    GroupName: string;
    isExpertOnly: boolean;
}
export interface ActionInfo {
    id: number;
    name: string;
    paramTypeList: string;
}
export interface DeviceRegisteredActions {
    ActionButtons: Array<ActionButton>;
    ActionList: Array<ActionInfo>;
    ActionType: number;
    id: number;
}
export interface DeviceActionRequestData {
    ActionId: number;
    ActionType: number;
    ParamArray: Array<number>;
    SenderId: number;
    UniqueActionRequestId: number;
}
export interface ApiOpcuaReqData {
    ActionRequestData: DeviceActionRequestData;
    checkSum: number;
    id: number;
    Sts: number;
}
export interface ApiOpcuaData {
    HmiReq: ApiOpcuaReqData;
    HmiResp: ApiOpcuaReqData;
    InternalReq: ApiOpcuaReqData;
    InternalResp: ApiOpcuaReqData;
    OrchReq: ApiOpcuaReqData;
    OrchResp: ApiOpcuaReqData;
    Req: ApiOpcuaReqData;
    Resp: ApiOpcuaReqData;
}
export interface AxisInterlockCfgData {
    Description: string;
    Direction: number;
    Ignored: boolean;
    InterlockType: number;
    SenderId: number;
    TargetId: number;
}
export interface DeviceCfg {
    AutoReset: boolean;
    ControllableByHmi: boolean;
    Ignore: boolean;
    OutboundAxisInterlocks: Array<AxisInterlockCfgData>;
    SafetyZoneId: number;
}
export interface FaultData {
    AutoReset: boolean;
    Code: number;
    DeviceId: number;
    LogFlag: boolean;
    Msg: string;
    ParentStepNum: number;
    ResetFlag: boolean;
    StepNum: number;
    TimeStamp: bigint | number;
}
export interface DeviceFaultData {
    ChildrenPresent: boolean;
    List: Array<FaultData>;
    Present: boolean;
}
export interface ProcessData {
    ActiveId: number;
    ActiveName: string;
    DeviceStateThatCalled: number;
    DeviceStepThatCalled: number;
    firstScan: boolean;
    isDone: boolean;
    isError: boolean;
    isStepNum: number;
    LastId: number;
    NextStepNum: number;
    ParamArray: Array<number>;
    RequestId: number;
    RequestParamArray: Array<number>;
    SenderId: number;
    StepDescription: string;
    StepTime: bigint | number;
    UniqueActionRequestId: number;
}
export interface DeviceInstants {
    InstantKill_ON: boolean;
    InstantManual_ON: boolean;
    InstantReset_ON: boolean;
    InstantStop_ON: boolean;
}
export interface DeviceSts {
    Aborting: boolean;
    AllChildrenIdle: boolean;
    AllChildrenIdleOrError: boolean;
    AllChildrenInactive: boolean;
    AllChildrenKilled: boolean;
    ColorCode: number;
    CommanderId: number;
    Done: boolean;
    Error: boolean;
    Idle: boolean;
    IdleOrError: boolean;
    IIFKM: boolean;
    Inactive: boolean;
    IPR: boolean;
    KEI: boolean;
    Killed: boolean;
    Manual: boolean;
    Paused: boolean;
    PauseRequested: boolean;
    RecordingLogs: boolean;
    Resetting: boolean;
    RRI: boolean;
    Running: boolean;
    RunningOrStopping: boolean;
    State: number;
    StatusMsg: string;
    StepDescription: string;
    StepNum: number;
    Stopping: boolean;
}
export enum DeviceTypes {
    BASE = 0,
    AXIS = 1,
    BOSCHAXIS = 2,
    DUALAXIS = 3,
    GANTRY = 4,
    SYSTEM = 5,
    BRIDGE = 6,
    CONDUCTOR = 7,
    ROBOT = 8,
    EOAT = 9,
    VISION = 10,
    TWOPOS = 11,
    TWOPOSGANTRY = 12,
    EXTSERVICE = 13,
    HMI = 14,
}
export interface DeviceRegistration {
    ChildIdArray: Array<number>;
    DeviceType: DeviceTypes;
    Id: number;
    isExternalService: boolean;
    Mnemonic: string;
    ParentId: number;
}
export interface DeviceSettings {
    Bypass: boolean;
}
export interface UdpData {
    StreamVal: number;
}
export interface Device {
    ApiOpcua: ApiOpcuaData;
    Cfg: DeviceCfg;
    connectionStatus: boolean;
    Errors: DeviceFaultData;
    ExecMethod: ProcessData;
    instants: DeviceInstants;
    Is: DeviceSts;
    Mission: ProcessData;
    MutedChildrenArray: Array<boolean>;
    Process: ProcessData;
    Registration: DeviceRegistration;
    Script: ProcessData;
    Settings: DeviceSettings;
    SkipKillDuringAbortChildren: Array<boolean>;
    Task: ProcessData;
    Udp: UdpData;
    Warnings: DeviceFaultData;
}
export interface SystemFaultData {
    List: Array<FaultData>;
    Present: boolean;
}
export interface LogRecordData {
    LastIndex: number;
    List: Array<DebugLogData>;
}
export interface MachineRetainParameters {
    CellType: number;
    Location: string;
    MachineSerialNumber: string;
    SafetyControllerSerialNumber: string;
}
export interface DeviceInput {
    Id: number;
    Name: string;
    ParentId: number;
}
export interface SettingsAllUsers {
    PlaceholderBool: boolean;
}
export interface SettingsExpert {
    AutoLogoutTime: Date | string;
    DryCycle: boolean;
    ExpertStaysLoggedIn: boolean;
    OverridesEnabled: boolean;
}
export interface Settings {
    AllUsers: SettingsAllUsers;
    Expert: SettingsExpert;
}
export interface UserData {
    ActiveUser: number;
    Login_REQ: boolean;
    Logout_REQ: boolean;
    Password: string;
    TimeLeftBeforeAutoLogout_MIN: number;
    Username: string;
}
export interface UtilityData {
    Always_OFF: boolean;
    Always_ON: boolean;
    CurrentSysTime: bigint | number;
    CurrentTimeMs: bigint | number;
    FirstScan: boolean;
    Flash_1SEC: boolean;
    Flash_250MSEC: boolean;
    Flash_2SEC: boolean;
    Flash_500MSEC: boolean;
    Flash_50MSEC: boolean;
    Flash_5SEC: boolean;
    OneShot_1SEC: boolean;
    OneShot_50MSEC: boolean;
    RunningTimeSec: bigint | number;
    StartupTimeBeyond15Sec: boolean;
    StartupTimeBeyond30Sec: boolean;
    StartupTimeBeyondOneMinute: boolean;
}

export type Machine = {
    ActiveUserId: number;
    Cfg: MachineCfg;
    ClearFltsCmd: boolean;
    CurrentTimeMs: bigint | number;
    DateAndTime: Date | string;
    DateAndTimeString: string;
    DeviceLogs: Array<DeviceLogData>;
    DeviceRegisteredActions: DeviceRegisteredActions;
    Devices: Array<Device>;
    Errors: SystemFaultData;
    EstopCircuit_OK: boolean;
    EstopCircuitDelayed_OK: boolean;
    EthercatMaster_OK: boolean;
    EthercatSlaves_OK: boolean;
    FenceCircuit_OK: boolean;
    GuardDoors_LOCKED: boolean;
    HeartbeatHMI: number;
    HeartbeatPLC: number;
    MachineLog: LogRecordData;
    MachineRetainParameters: MachineRetainParameters;
    ManualMode: boolean;
    NetworkHealth_OK: boolean;
    RegisteredDevices: Array<DeviceRegistration>;
    RegisteredInputs: Array<DeviceInput>;
    ResetEthercat_REQ: boolean;
    Settings: Settings;
    SupplyAir_OK: boolean;
    SyncClockDone: boolean;
    SyncClockReq: boolean;
    SyncClockTime: bigint | number;
    User: UserData;
    Utilities: UtilityData;
    Warnings: SystemFaultData;
};
export type MachineTypeRoot = {
    ActiveUserId: number;
    Cfg: MachineCfg;
    ClearFltsCmd: boolean;
    CurrentTimeMs: bigint | number;
    DateAndTime: Date | string;
    DateAndTimeString: string;
    DeviceLogs: Array<DeviceLogData>;
    DeviceRegisteredActions: DeviceRegisteredActions;
    Devices: Array<Device>;
    Errors: SystemFaultData;
    EstopCircuit_OK: boolean;
    EstopCircuitDelayed_OK: boolean;
    EthercatMaster_OK: boolean;
    EthercatSlaves_OK: boolean;
    FenceCircuit_OK: boolean;
    GuardDoors_LOCKED: boolean;
    HeartbeatHMI: number;
    HeartbeatPLC: number;
    MachineLog: LogRecordData;
    MachineRetainParameters: MachineRetainParameters;
    ManualMode: boolean;
    NetworkHealth_OK: boolean;
    RegisteredDevices: Array<DeviceRegistration>;
    RegisteredInputs: Array<DeviceInput>;
    ResetEthercat_REQ: boolean;
    Settings: Settings;
    SupplyAir_OK: boolean;
    SyncClockDone: boolean;
    SyncClockReq: boolean;
    SyncClockTime: bigint | number;
    User: UserData;
    Utilities: UtilityData;
    Warnings: SystemFaultData;
};
