// This file is generated by machine-bridge/src/type-generator/generate-machine-types.ts
// Output location defaults to machine-bridge/generated-types/shared/types.ts.
// Do not edit by hand; rerun the generator against a live OPC UA server.

export const machineTypeSource = {
    "controllerName": "CODESYS Control for Linux SL",
    "endpoint": "opc.tcp://127.0.0.1:4840",
    "generatedAt": "2026-07-22T22:03:52.645Z",
    "rootNodeId": "ns=4;s=|var|CODESYS Control for Linux SL.Application.Machine_00251",
    "rootTag": "Machine_00251"
} as const;

export enum RctrlControllerTypes {
    UNKNOWN = 0,
    ABB = 1,
}
export interface AxisMotionProfileData {
    acceleration: number;
    jerk: number;
    speed: number;
}
export interface RobPositionData {
    pdeg: number;
    rdeg: number;
    toolFrameId: number;
    userFrameId: number;
    wdeg: number;
    x: number;
    y: number;
    z: number;
}
export interface CoordinateFrame {
    id: number;
    location: RobPositionData;
    name: string;
}
export interface RctrlCfg {
    atLinearPosTol: number;
    atRotationalPosTol: number;
    controllerId: number;
    controllerType: RctrlControllerTypes;
    ignoreLimitSwitches: boolean;
    ignores: Array<boolean>;
    ignoreSoftwareLimits: boolean;
    linearUnit: string;
    motionProfiles: Array<AxisMotionProfileData>;
    positions: Array<RobPositionData>;
    rotationalUnit: string;
    toolFrames: Array<CoordinateFrame>;
    userFrames: Array<CoordinateFrame>;
}
export interface ApplicatorSetpoint {
    ballValveOn: boolean;
    speed: number;
    squeegeeDiameter: number;
    stepperPosition: number;
    zOffset: number;
}
export interface AbbDataOutputs {
    applicatorCollisionPayloadOffset: number;
    applicatorPreloadPauseDuration: number;
    applicatorSetpoints: Array<ApplicatorSetpoint>;
    applicatorToolId: number;
    applicatorToolPresent: boolean;
    brushIsActive: boolean;
    brushLinearSpeed: number;
    brushToolPresent: boolean;
    cameraId: number;
    cameraSpeed: number;
    cameraToolPresent: boolean;
    cleanerId: number;
    clearErrorsReq: boolean;
    deviceCmdReqId: number;
    dryCycle: boolean;
    eoatPickDone: boolean;
    eoatReleaseDone: boolean;
    execMethodReqId: number;
    falseBottomStaysOpen: boolean;
    gripperIsClosed: boolean;
    gripperIsOpen: boolean;
    heartbeatVal: number;
    killReq: boolean;
    moveToNextSetpointOK: boolean;
    pauseReq: boolean;
    plcPartState: number;
    recordingIsActive: boolean;
    resetReq: boolean;
    squeegeeAtHome: boolean;
    startReq: boolean;
    stopReq: boolean;
    tareDone: boolean;
    taskParam0: number;
    taskParam1: number;
    taskParam2: number;
    taskParam3: number;
    taskReqId: number;
    transferPartDataDone: boolean;
    tubeHeightMax: number;
    tubeMassKg: number;
    tubeOuterDiameterMax: number;
    tubeTypeId: number;
    unclampPartDone: boolean;
    uniqueTaskReqId: number;
    updatePartDataDone: boolean;
    weighingFingerId: number;
    weighToolPresent: boolean;
    weighTubeDone: boolean;
}
export interface RctrlHmiManual {
    abbDataOutputs: AbbDataOutputs;
}
export interface AbbDataInputs {
    activePartLocationId: number;
    activeTaskId: number;
    activeToolId: number;
    activeToolVariantId: number;
    actualWaypoint: number;
    autoRecoverOK: boolean;
    autoRecoveryNeeded: boolean;
    brushStartReq: boolean;
    brushStopReq: boolean;
    controllerErrorId: number;
    eoatPickReq: boolean;
    eoatReleaseReq: boolean;
    errorId: number;
    flipBit: boolean;
    gripperCloseReq: boolean;
    gripperOpenReq: boolean;
    heartbeatVal: number;
    inTransitZone: boolean;
    lastCrossedSetpointId: number;
    lastTaskId: number;
    newPartState: number;
    recordingStartReq: boolean;
    recordingStopReq: boolean;
    recoverTaskId: number;
    recoveryTaskStepNum: number;
    recoveryWaypointId: number;
    startingWaypoint: number;
    stepNum: number;
    tareReq: boolean;
    targetWaypoint: number;
    taskStepNum: number;
    tcpPosX: number;
    tcpPosY: number;
    tcpPosZ: number;
    tcpRotP: number;
    tcpRotR: number;
    tcpRotW: number;
    tcPSpeed: number;
    transferDataCurrentPartLocationId: number;
    transferDataTargetPartLocationId: number;
    transferPartDataReq: boolean;
    unclampPartReq: boolean;
    uniqueTaskActiveId: number;
    updatePartDataReq: boolean;
    weighTubeReq: boolean;
    zOffsetFromFalseBottom: number;
}
export interface AbbSysOutputs {
    autoOn: boolean;
    controlOnState: boolean;
    cycleOn: boolean;
    emergencyStop_NOT_OK: boolean;
    executionError: boolean;
    limitSpeed: number;
    motorsOffState: boolean;
    motorsOnState: boolean;
    runChainOk: boolean;
}
export interface AbbInputs {
    data: AbbDataInputs;
    sysOutputs: AbbSysOutputs;
}
export interface AbbSysInputs {
    loadAndStart: boolean;
    motorsOff: boolean;
    motorsOn: boolean;
    stop: boolean;
}
export interface AbbOutputs {
    data: AbbDataOutputs;
    sysInputs: AbbSysInputs;
}
export interface AbbControllerInterface {
    i: AbbInputs;
    o: AbbOutputs;
}
export interface RctrlSts {
    activeToolId: number;
    actualPosition: RobPositionData;
    actualTCPSpeed: number;
    actualWaypoint: number;
    iController: AbbControllerInterface;
    isAtPosAndStandstill: boolean;
    isConnected: boolean;
    isJogging: boolean;
    isMoving: boolean;
    isStandstill: boolean;
    isTeachMode: boolean;
    robotProgramIsCyclingInAuto: boolean;
    targetPosition: RobPositionData;
    targetWaypoint: number;
}
export interface RecipeData {
    applicatorCollisionPayloadOffset: number;
    applicatorHasVariableSqueegee: boolean;
    applicatorPreloadPauseDuration: number;
    applicatorSetpoints: Array<ApplicatorSetpoint>;
    applicatorToolId: number;
    applicatorToolString: string;
    brushToolSpeed_RPM: number;
    cameraId: number;
    cameraSpeed: number;
    cameraString: string;
    cleanerId: number;
    cleanerString: string;
    dbId: string;
    falseBottomStaysOpen: boolean;
    index: number;
    linerPotPressure: number;
    linerTypeString: string;
    linerWeightMax: number;
    linerWeightMin: number;
    measuredSqueegeeDiaAtSetpoint1: number;
    nickname: string;
    robotSpeedWhileBrushing: number;
    tubeHeightMax: number;
    tubeMassKg: number;
    tubeOuterDiameterMax: number;
    tubeTypeId: number;
    tubeTypeString: string;
    usesBrushTool: boolean;
    usesCentrifuge: boolean;
    weighingFingerId: number;
    weighingFingerString: string;
}
export enum TwoPosDeviceOutputModes {
    MAINTAINED = 0,
    AUTORESET = 1,
}
export enum TwoPosDeviceSensorModes {
    DEFAULT = 0,
    STICKY = 1,
}
export enum TwoPosValveTypes {
    UNKNOWN = 0,
    V5_3_EXHAUST = 1,
    V5_3_CLOSED = 2,
    V4_2 = 3,
    V3_2_EXHAUST = 4,
}
export interface TwoPosCfg {
    labelA: string;
    labelB: string;
    missingSensA: boolean;
    missingSensB: boolean;
    moveTimeAtoB: Date | string;
    moveTimeBtoA: Date | string;
    outputMode: TwoPosDeviceOutputModes;
    sensorMode: TwoPosDeviceSensorModes;
    solPwrNotOnEstopCircuit: boolean;
    valveType: TwoPosValveTypes;
}
export interface TwoPosSts {
    actualPosition: number;
    atPosA: boolean;
    atPosB: boolean;
    overrideA: boolean;
    overrideB: boolean;
    permA: boolean;
    permB: boolean;
    stickyA: boolean;
    stickyB: boolean;
}
export interface ConCfg {
    placeholder: boolean;
}
export enum Priorities {
    NONE = 0,
    RECOVER_ROBOT = 1,
    CALIBRATE_GRIPPER = 2,
    ACTIVATE_RECIPE = 3,
    PERFORM_CHANGEOVER = 4,
    CALIBRATE_SQUEEGEE = 5,
    ENTER_JOB_DATA = 6,
    LOAD_RAW_TUBES = 10,
    ENTER_BATCH_DATA = 11,
    PRIME_APPLICATOR = 13,
    START_POT_PRESSURIZATION = 15,
    PRE_WEIGH_TUBES = 20,
    APPLY_LINER = 30,
    SPIN_TUBES = 33,
    BRUSH_LINER = 35,
    START_POT_DEPRESSURIZATION = 39,
    PHOTOGRAPH_TUBES = 40,
    POST_WEIGH_TUBES = 50,
    PREP_FOR_UNLOAD = 60,
    REVIEW_VIDEOS = 70,
    SAVE_BATCH_DATA = 80,
    UNLOAD_PARTS = 85,
    DONE = 1000,
}
export interface ConSts {
    activePriority: Priorities;
}
export enum DeviceIds {
    ABB = 11,
    EOAT = 12,
    VIS = 13,
    FIX_T = 14,
    FIX_S = 15,
    CLAMP_T = 16,
    CLAMP_S = 17,
    FLSB_T = 18,
    FLSB_S = 19,
    POT = 20,
    SQUEE = 21,
    GRIP = 22,
    WEIGH = 23,
}
export interface TwoPosGantryPoseChildPosition {
    childId: number;
    positionId: number;
}
export interface TwoPosGantryPose {
    childPositions: Array<TwoPosGantryPoseChildPosition>;
}
export interface TwoPosGantryCfg {
    numAxes: number;
    poses: Array<TwoPosGantryPose>;
    useSimultaneousMoves: boolean;
}
export interface TwoPosGantrySts {
    actualPosition: number;
}
export interface HmiCfg {
    hasMultipleKiosks: boolean;
    startingScreen: string;
}
export enum ActionTypes {
    MISSION = 0,
    CMD = 1,
    TASK = 2,
    PROCESS = 3,
    EXEC_METHOD = 4,
    SCRIPT = 5,
    COUNT = 6,
}
export interface DeviceActionRequestData {
    actionId: number;
    actionType: ActionTypes;
    paramArray: Array<number>;
    senderId: number;
    uniqueActionRequestId: number;
}
export interface ApiOpcuaReqData {
    actionRequestData: DeviceActionRequestData;
    checkSum: number;
    id: number;
    sts: number;
}
export interface ApiOpcuaData {
    hmiReq: ApiOpcuaReqData;
    hmiResp: ApiOpcuaReqData;
    internalReq: ApiOpcuaReqData;
    internalResp: ApiOpcuaReqData;
    orchReq: ApiOpcuaReqData;
    orchResp: ApiOpcuaReqData;
    req: ApiOpcuaReqData;
    resp: ApiOpcuaReqData;
}
export interface AxisInterlockCfgData {
    description: string;
    direction: number;
    ignored: boolean;
    interlockType: number;
    senderId: number;
    targetId: number;
}
export interface DeviceCfg {
    autoReset: boolean;
    controllableByHmi: boolean;
    ignore: boolean;
    outboundAxisInterlocks: Array<AxisInterlockCfgData>;
    safetyZoneId: number;
}
export interface FaultData {
    autoReset: boolean;
    code: number;
    deviceId: number;
    logFlag: boolean;
    msg: string;
    parentStepNum: number;
    resetFlag: boolean;
    stepNum: number;
    timeStamp: bigint | number;
}
export interface DeviceFaultData {
    childrenPresent: boolean;
    list: Array<FaultData>;
    present: boolean;
}
export interface ProcessData {
    activeId: number;
    activeName: string;
    deviceStateThatCalled: number;
    deviceStepThatCalled: number;
    firstScan: boolean;
    isDone: boolean;
    isError: boolean;
    isStepNum: number;
    lastId: number;
    nextStepNum: number;
    paramArray: Array<number>;
    requestId: number;
    requestParamArray: Array<number>;
    senderId: number;
    stepDescription: string;
    stepTime: bigint | number;
    uniqueActionRequestId: number;
}
export interface DeviceInstants {
    instantKill_ON: boolean;
    instantManual_ON: boolean;
    instantReset_ON: boolean;
    instantStop_ON: boolean;
}
export enum Colors {
    BLACK = 0,
    RED = 1,
    ORANGE = 2,
    YELLOW = 3,
    GREEN = 4,
    BLUE = 5,
    INDIGO = 6,
    VIOLET = 7,
    GRAY = 8,
    WHITE = 9,
    LIGHTBLACK = 10,
    LIGHTRED = 11,
    LIGHTORANGE = 12,
    LIGHTYELLOW = 13,
    LIGHTGREEN = 14,
    LIGHTBLUE = 15,
    LIGHTINDIGO = 16,
    LIGHTVIOLET = 17,
    LIGHTGRAY = 18,
    LIGHTWHITE = 19,
    DARKRED = 201,
    DARKYELLOW = 203,
    DARKGRAY = 208,
    OPAQUEWHITE = 309,
    LIGHT = 1001,
    DARK = 1002,
    ACTIONBTN1 = 21,
    ACTIONBTN2 = 22,
    ACTIONBTN3 = 23,
    ACTIONBTN4 = 24,
    ACTIONBTN5 = 25,
    ACTIONBTN6 = 26,
    GOOD = 31,
    WARN = 32,
    ERROR = 33,
    KILLED = 40,
    INACTIVE = 41,
    RESETTING = 42,
    IDLE = 43,
    RUNNING = 44,
    DONE = 45,
    ABORTING = 46,
    MANUAL = 47,
    PAUSED = 48,
    FAULTED = 49,
    STOPPING = 440,
    TASKDONE = 50,
    TASKACTIVE = 51,
    TASKFUTURE = 52,
    FANUCYELLOW = 60,
    EMPTY = 100,
    PROCESSING = 101,
    RAW = 102,
    DEBURRED = 103,
    MACHINED = 104,
    WASHED = 105,
    DRYED = 106,
    SCRAPPED = 109,
    FINISHED = 110,
    DEBURRBOTTOMFINSHED = 111,
    NEXTPART = 115,
    DELETE = 116,
}
export enum States {
    ABORTING = 4294967293,
    ERROR = 4294967294,
    KILLED = 4294967295,
    INACTIVE = 0,
    RESETTING = 50,
    IDLE = 100,
    RUNNING = 500,
    STOPPING = 900,
    PAUSED = 999,
    DONE = 1000,
    MANUAL = 1100,
}
export interface DeviceSts {
    aborting: boolean;
    allChildrenIdle: boolean;
    allChildrenIdleOrError: boolean;
    allChildrenInactive: boolean;
    allChildrenKilled: boolean;
    colorCode: Colors;
    commanderId: number;
    done: boolean;
    error: boolean;
    idle: boolean;
    idleOrError: boolean;
    IIFKM: boolean;
    inactive: boolean;
    IPR: boolean;
    KEI: boolean;
    killed: boolean;
    manual: boolean;
    paused: boolean;
    pauseRequested: boolean;
    recordingLogs: boolean;
    resetting: boolean;
    RRI: boolean;
    running: boolean;
    runningOrStopping: boolean;
    state: States;
    statusMsg: string;
    stepDescription: string;
    stepNum: number;
    stopping: boolean;
}
export enum DeviceTypes {
    BASE = 0,
    AXIS = 1,
    BOSCHAXIS = 2,
    DUALAXIS = 3,
    GANTRY = 4,
    SYSTEM = 5,
    BRIDGE = 6,
    CONDUCTOR = 7,
    ROBOT = 8,
    EOAT = 9,
    VISION = 10,
    TWOPOS = 11,
    TWOPOSGANTRY = 12,
    EXTSERVICE = 13,
    HMI = 14,
}
export interface DeviceRegistration {
    childIdArray: Array<number>;
    deviceType: DeviceTypes;
    id: number;
    isExternalService: boolean;
    mnemonic: string;
    parentId: number;
}
export interface DeviceSettings {
    bypass: boolean;
}
export interface UdpData {
    streamVal: number;
}
export interface Device {
    apiOpcua: ApiOpcuaData;
    cfg: DeviceCfg;
    connectionStatus: boolean;
    errors: DeviceFaultData;
    execMethod: ProcessData;
    instants: DeviceInstants;
    is: DeviceSts;
    mission: ProcessData;
    mutedChildrenArray: Array<boolean>;
    process: ProcessData;
    registration: DeviceRegistration;
    script: ProcessData;
    settings: DeviceSettings;
    skipKillDuringAbortChildren: Array<boolean>;
    task: ProcessData;
    udp: UdpData;
    warnings: DeviceFaultData;
}
export interface ComponentAnimation {
    accentColor: number;
    backgroundColor: number;
    fontColor: number;
    needsExpertUser: boolean;
    visibility: number;
    wasClicked: boolean;
}
export interface HmiDevCtrlData {
    pbClear: ComponentAnimation;
    pbRelease: ComponentAnimation;
    pbReset: ComponentAnimation;
    pbStart: ComponentAnimation;
    pbStop: ComponentAnimation;
    pbTake: ComponentAnimation;
}
export interface ButtonBar {
    clearFaultsBtn: ComponentAnimation;
    energizeBtn: ComponentAnimation;
    jobChangeBtn: ComponentAnimation;
    loadBtn: ComponentAnimation;
    lockBtn: ComponentAnimation;
    resetBtn: ComponentAnimation;
    resetCncBtn: ComponentAnimation;
    startBtn: ComponentAnimation;
    stopBtn: ComponentAnimation;
    unloadBtn: ComponentAnimation;
    unlockBtn: ComponentAnimation;
}
export type BYTE = number | string | unknown;
export interface StatusBar {
    bannerMode: number;
    batchQty: number;
    cncTimeLeft: Date | string;
    dateAndTime: Date | string;
    faultCodeData: FaultData;
    goodCnt: number;
    jobName: string;
    partNumber: string;
    status: number;
    statusMsg: number;
}
export interface HmiSts {
    activeCodesysHmiScreenName: string;
    activeDev: Device;
    activeDevCtrl: HmiDevCtrlData;
    activeDeviceId: number;
    activeKioskId: number;
    buttonBar: ButtonBar;
    heartbeatHMI: BYTE;
    heartbeatPLC: BYTE;
    isConnected: boolean;
    remoteControlPage: number;
    statusBar: StatusBar;
}
export interface TwoPosInputs {
    sensA_ON: boolean;
    sensB_ON: boolean;
}
export interface RailBrakeInputs {
    railBrake1_CLOSED: boolean;
    railBrake1_ERROR: boolean;
    railBrake1_OPEN: boolean;
    railBrake2_CLOSED: boolean;
    railBrake2_ERROR: boolean;
    railBrake2_OPEN: boolean;
}
export interface AxisInputs {
    brakes: RailBrakeInputs;
    sensors: Array<boolean>;
}
export interface FixInputs {
    partPresentSensors: Array<boolean>;
}
export interface PressureSwitchInputs {
    actualPressure_PSI: number;
    AT_PRESSURE: boolean;
    TOO_HIGH: boolean;
}
export interface PotInputs {
    ballValve_CLOSED: boolean;
    ballValve_OPENED: boolean;
    potPressureSw: PressureSwitchInputs;
}
export interface RobInputs {
    applicatorCalibrationSw_ON: boolean;
    applicatorTool_PRESENT: boolean;
    brushTool_PRESENT: boolean;
    cameraTool_PRESENT: boolean;
    gripperTool_PRESENT: boolean;
}
export interface GuardLockInputs {
    LOCKED: boolean;
    requestToEnterPb_ON: boolean;
    safeInputs_OK: boolean;
    solenoid_UNLOCKED: boolean;
    TONGUE_IN: boolean;
}
export interface SftyInputs {
    doorSwitches_ALL_OK: boolean;
    estopCircuit_OK: boolean;
    estopCircuitDelayed_OK: boolean;
    estopCircuitInputs_ALL_ON: boolean;
    estopCircuitReset_READY: boolean;
    estopInputs: Array<boolean>;
    estopPbs_ALL_OK: boolean;
    fenceCircuit_OK: boolean;
    fenceCircuitInputs_ALL_ON: boolean;
    fenceCircuitReset_READY: boolean;
    fenceConditionForEstop_OK: boolean;
    guardLocks: Array<GuardLockInputs>;
    psc1AlarmCode: number;
    psc1AlarmMsg: string;
    psc1FatalErrorCode: number;
    psc1FatalErrorMsg: string;
    psc1StatusCode: number;
    psc1StatusMsg: string;
    safeContactorsNC_OK: boolean;
    safeNC_ALL_OK: boolean;
    safeValveNC_OK: boolean;
    unlockGuardDoors_OUT: boolean;
}
export interface SysInputs {
    powerSupplies_OK: Array<boolean>;
    pressureSwitches: Array<PressureSwitchInputs>;
}
export interface inputs {
    CLAMP_S: TwoPosInputs;
    CLAMP_T: TwoPosInputs;
    dummy: AxisInputs;
    EOAT: TwoPosInputs;
    FIX_S: FixInputs;
    FIX_T: FixInputs;
    FLSB_S: TwoPosInputs;
    FLSB_T: TwoPosInputs;
    GRIP: TwoPosInputs;
    POT: PotInputs;
    ROB: RobInputs;
    SFTY: SftyInputs;
    SQUEE: AxisInputs;
    SYS: SysInputs;
}
export interface JobData {
    activeBatchNumber: number;
    activeRecipeIndex: number;
    assemblyName: string;
    assemblyNumber: string;
    batchId: string;
    batchSts: number;
    goodCnt: number;
    jobCompleted: boolean;
    jobEndTime: string;
    jobName: string;
    jobStartTime: string;
    lotId: string;
    lotQty: number;
    operationNumber: string;
    operatorId: string;
    salesOrderId: string;
    scrapCnt: number;
    setupCompleted: boolean;
    setupEndTime: string;
    setupStartTime: string;
    tubeTypeString: string;
    workInstruction: string;
    workOrderId: string;
}
export interface TwoPosOutputs {
    outA: boolean;
    outB: boolean;
}
export interface PotOutputs {
    ballValveOpen_REQ: boolean;
    paintPot: TwoPosOutputs;
    pressureSetpoint_PSI: number;
}
export interface StrainGaugeInputs {
    calbrationNextStepReq: boolean;
    calibrateReq: boolean;
    referenceWeight_g: number;
    sampleReq: boolean;
    tareReq: boolean;
}
export interface RobOutputs {
    loadCell: StrainGaugeInputs;
}
export interface GuardLockOutputs {
    requestToEnterPb_FLASH: boolean;
    requestToEnterPb_ILLUM: boolean;
    unlock_REQ: boolean;
}
export interface SftyOutputs {
    clearControllerAlarm_REQ: boolean;
    controllerAlarm_CLEAR: boolean;
    estopCircuit_RESET: boolean;
    estopPbIllumns: Array<boolean>;
    guardLocks: Array<GuardLockOutputs>;
    requestToEnterPb_ON: boolean;
    resetPb_FLASH: boolean;
    resetPb_ILLUM: boolean;
    robotTeachMode_ON: boolean;
}
export interface WeidmullerIoPwmOutput {
    controlWord: number;
    pulseDuration: number;
}
export interface SysOutputs {
    green_ON: boolean;
    red_ON: boolean;
    startPb_FLASH: boolean;
    startPb_ILLUM: boolean;
    yellow_ON: boolean;
}
export interface outputs {
    CLAMP_S: TwoPosOutputs;
    CLAMP_T: TwoPosOutputs;
    EOAT: TwoPosOutputs;
    FLSB_S: TwoPosOutputs;
    FLSB_T: TwoPosOutputs;
    GRIP: TwoPosOutputs;
    POT: PotOutputs;
    ROB: RobOutputs;
    SFTY: SftyOutputs;
    SQUEE: WeidmullerIoPwmOutput;
    SYS: SysOutputs;
}
export enum PartStates {
    EMPTY = 0,
    UNVALIDATEDRAW = 10,
    RAW = 20,
    STARTEDPREWEIGHING = 29,
    PREWEIGHED = 30,
    STARTEDAPPLYING = 31,
    LINERAPPLIED = 40,
    STARTEDLINERBRUSHING = 41,
    LINERBRUSHED = 50,
    LINERSPUN = 60,
    STARTEDPHOTOGRAPHING = 61,
    PHOTOGRAPHED = 70,
    STARTEDPOSTWEIGHING = 71,
    POSTWEIGHED = 80,
    SCRAPPED = 900,
    FAILED = 911,
    PASSED = 1000,
}
export enum PartValidationStates {
    NONE = 0,
    SCRAPPED_GENERIC = 1,
    SCRAPPED_LINER_APPLICATION_STARTED_BUT_NOT_FINISHED = 101,
    SCRAPPED_LINER_BRUSHING_STARTED_BUT_NOT_FINISHED = 102,
    SCRAPPED_FAILED_WEIGHT_TOO_LIGHT = 701,
    SCRAPPED_FAILED_WEIGHT_TOO_HEAVY = 702,
    SCRAPPED_FAILED_IMAGE_REVIEW_GENERAL = 800,
    SCRAPPED_FAILED_IMAGE_REVIEW_GAPS_IN_SMEAR = 801,
    SCRAPPED_FAILED_IMAGE_REVIEW_BUBBLES = 802,
    PASSED = 1000,
}
export interface PartValidationData {
    linerWeight_g: number;
    postWeight_g: number;
    preWeight_g: number;
    serialNumber: string;
    statusMsg: string;
    timestampVision_sec: number;
    visionSts: PartValidationStates;
    weightSts: PartValidationStates;
}
export interface PartData {
    fixtureLocationWhenLoaded: number;
    inFixture: boolean;
    loadedBadSensor: boolean;
    processSts: PartStates;
    validation: PartValidationData;
}
export interface PartDataStatus {
    activeCnt: number;
    allFixturesAreEmpty: boolean;
    finishedCnt: number;
    lowestPartStatus: PartStates;
    oneOrMoreRejectPartsInCell: boolean;
    oneOrMoreRejectPartsInRobot: boolean;
    parts: Array<PartData>;
    robotHasOneFinishedPart: boolean;
    robotHasOneRaw: boolean;
    robotIsEmpty: boolean;
    shortFixtureIsEmpty: boolean;
    tallFixtureIsEmpty: boolean;
    videosNeedReviewed: boolean;
}
export interface PotCfg {
    placeholder: boolean;
}
export interface PotSts {
    actualPressure: number;
    atTargetPressure: boolean;
    ballValve_CLOSED: boolean;
    ballValve_OPEN: boolean;
    cfg: PotCfg;
    isDepressurized: boolean;
    isPressurizing: boolean;
    linerIsFlowing: boolean;
    state: number;
    targetPressure: number;
}
export interface RecipeStore {
    numRecipes: number;
    recipes: Array<RecipeData>;
}
export interface RobCfg {
    placeholder: boolean;
}
export interface AdjustedSetpoint {
    moveTimeSec: number;
    robotMoveTimeSec: number;
    robotVelocity: number;
    robotZOffset: number;
    stepperSpeed: number;
}
export interface RobMeta {
    adjustedSetpoints: Array<AdjustedSetpoint>;
    applicatorSqueegeeMidlineOffset: number;
}
export interface StrainGaugeSts {
    calibOffset: number;
    calibScaleFactor: number;
    currentValue: number;
    rawValue: number;
    sampledStdDev: number;
    sampledValue: number;
    sampledValueRaw: number;
    state: number;
    statusMsg: string;
    tareOffset: number;
    unit: string;
}
export interface RobSts {
    activeToolDeviceId: number;
    activeToolId: number;
    actualApplicatorZPositionRFB: number;
    actualApplicatorZVelocityRFB: number;
    actualPosition: RobPositionData;
    actualRobotZPositionRFB: number;
    actualWaypoint: number;
    actualZone: number;
    applicatorHasBeenPrimed: boolean;
    applicatorIsDirty: boolean;
    applyLinerStartSetpointMovesReq: boolean;
    autoRecoveryNeeded: boolean;
    autoRecoveryOk: boolean;
    cameraIsRecording: boolean;
    gripperIsCalibrated: boolean;
    iController: AbbControllerInterface;
    lastCrossedApplyLinerSetpointId: number;
    lastRecordedLoadCellValue_g: number;
    loadCellCurrentValue_g: number;
    loadCellSts: StrainGaugeSts;
    moveToNextSetpointOK: boolean;
    squeegeeCalibrationOffset: number;
    squeegeeIsCalibrated: boolean;
    squeegeeIsHomed: boolean;
    targetWaypoint: number;
    unclampPartDone: boolean;
    visionIsCalibrated: boolean;
    weighTubeTareDone: boolean;
    weighTubeWeighDone: boolean;
}
export interface SftyCfg {
    numOfDoors: number;
}
export interface SftySts {
    placeholder: boolean;
}
export enum AxisDriveTypes {
    STINGRAY = 0,
    BOSCH_FSOE = 1,
    NANOTEC = 2,
    TEKNIC = 3,
    TEKNIC_DISCRETE_IO = 4,
}
export enum PositionReferencingMethods {
    NONE = 0,
    HOMING = 1,
    POSITION_VERIFICATION = 2,
    HOMING_TO_HARDSTOP = 3,
}
export interface SoftMotionScalingParams {
    gearOutputTurnsLeft: number;
    gearOutputTurnsRight: number;
    incrementsLeft: number;
    invertDir: boolean;
    motorsTurnsLeft: number;
    motorTurnsRight: number;
    unitsInApplicationRight: number;
}
export enum AxisSensors {
    NONE = 0,
    HOME_SW = 1,
    NEGATIVE_LIM_SW = 2,
    POSITIVE_LIM_SW = 3,
}
export interface AxisCfg {
    atPosTol: number;
    autoPositionVerifyDuringReset: boolean;
    axesPositionToleranceForSkew: number;
    axisType: number;
    driveId: number;
    driveType: AxisDriveTypes;
    gearingPositionTolerance: number;
    hardStopNegative: number;
    hardStopPositive: number;
    hasDynamicNegativeLimit: boolean;
    hasDynamicPositiveLimit: boolean;
    hasRailBrakes: boolean;
    homingMethod: number;
    homingToHardstopDir: number;
    ignoreLimitSwitches: boolean;
    ignores: Array<boolean>;
    ignoreSoftwareLimits: boolean;
    keepMasteredStatusAtStartup: boolean;
    maxCurrentNormalOperation: number;
    maxCurrentWhileHomingToHardstop: number;
    motionProfiles: Array<AxisMotionProfileData>;
    operationalPositionMax: number;
    operationalPositionMin: number;
    positionReferencingMethod: PositionReferencingMethods;
    scaleFactorUnitsPerEncoderCount: number;
    searchDistance: number;
    sensorPositions: Array<number>;
    shippingPosition: number;
    softMotionScalingParams: SoftMotionScalingParams;
    softwareLimitNegative: number;
    softwareLimitPositive: number;
    unit: string;
    updateScalingIsNeeded: boolean;
    validationSensor: AxisSensors;
    verificationSensorOffsetFromZero: number;
}
export enum AxisLimitEnforcements {
    UNKNOWN = 0,
    ENFORCED = 1,
    UNENFORCED = 2,
}
export enum DualAxisStopTypes {
    NONE = 0,
    NORMAL = 1,
    SLAVE_FAULT = 2,
    MASTER_FAULT = 3,
}
export interface AxisInterlockStsData {
    conditionsAreMet: boolean;
    isAllowed: boolean;
    isIgnoredByCfg: boolean;
    isOverridden: boolean;
    overridenTimeLeft: Date | string;
}
export interface AxisInterlockData {
    cfg: AxisInterlockCfgData;
    sts: AxisInterlockStsData;
}
export interface AxisInterlocks {
    list: Array<AxisInterlockData>;
}
export interface AxisPermissiveStsData {
    conditionsAreMet: boolean;
    isAllowed: boolean;
    isIgnoredByCfg: boolean;
    isOverridden: boolean;
}
export enum SM3ErrorSMCERROR {
    SMC_NO_ERROR = 0,
    SMC_DI_GENERAL_COMMUNICATION_ERROR = 1,
    SMC_DI_AXIS_ERROR = 2,
    SMC_DI_FIELDBUS_LOST_SYNCRONICITY = 3,
    SMC_DI_SWLIMITS_EXCEEDED = 10,
    SMC_DI_HWLIMITS_EXCEEDED = 11,
    SMC_DI_LINEAR_AXIS_OUTOFRANGE = 12,
    SMC_DI_HALT_OR_QUICKSTOP_NOT_SUPPORTED = 13,
    SMC_DI_VOLTAGE_DISABLED = 14,
    SMC_DI_IRREGULAR_ACTPOSITION = 15,
    SMC_DI_POSITIONLAGERROR = 16,
    SMC_DI_HOMING_ERROR = 17,
    SMC_DI_LICENSING_ERROR = 18,
    SMC_DI_DRIVE_LIMIT_ACTIVE = 19,
    SMC_REGULATOR_OR_START_NOT_SET = 20,
    SMC_WRONG_CONTROLLER_MODE = 21,
    SMC_INVALID_ACTION_FOR_LOGICAL = 25,
    SMC_AXIS_IS_NOT_OPERATIONAL = 27,
    SMC_FB_WASNT_CALLED_DURING_MOTION = 30,
    SMC_AXIS_IS_NO_AXIS_REF = 31,
    SMC_AXIS_REF_CHANGED_DURING_OPERATION = 32,
    SMC_FB_ACTIVE_AXIS_DISABLED = 33,
    SMC_AXIS_NOT_READY_FOR_MOTION = 34,
    SMC_AXIS_ERROR_DURING_MOTION = 35,
    SMC_FB_CALLED_FROM_WRONG_TASK = 36,
    SMC_VD_MAX_VELOCITY_EXCEEDED = 40,
    SMC_VD_MAX_ACCELERATION_EXCEEDED = 41,
    SMC_VD_MAX_DECELERATION_EXCEEDED = 42,
    SMC_3SH_INVALID_VELACC_VALUES = 50,
    SMC_3SH_MODE_NEEDS_HWLIMIT = 51,
    SMC_FRC_NO_FREE_HANDLE = 60,
    SMC_MAC_INITIALIZATION_FAILED = 65,
    SMC_MAC_INVALID_TASK_HANDLE = 66,
    SMC_MAC_TOO_MANY_TASKS = 67,
    SMC_MAC_ATOMIC_ADD_FAILED = 68,
    SMC_SDO_INVALID_DATALENGTH = 69,
    SMC_SCM_NOT_SUPPORTED = 70,
    SMC_SCM_AXIS_IN_WRONG_STATE = 71,
    SMC_SCM_INTERRUPTED = 72,
    SMC_ST_WRONG_CONTROLLER_MODE = 75,
    SMC_RAG_ERROR_DURING_STARTUP = 80,
    SMC_RAG_ERROR_AXIS_NOT_INITIALIZED = 81,
    SMC_PP_WRONG_AXIS_TYPE = 85,
    SMC_PP_NUMBER_OF_ABSOLUTE_BITS_INVALID = 86,
    SMC_NEGATIVE_MODULO_PERIOD = 87,
    SMC_CGR_ZERO_VALUES = 90,
    SMC_CGR_DRIVE_POWERED = 91,
    SMC_CGR_INVALID_POSPERIOD = 92,
    SMC_CGR_POSPERIOD_NOT_INTEGRAL = 93,
    SMC_FRACTION_TECH_UNITS_INVALID = 94,
    SMC_P_FTASKCYCLE_EMPTY = 110,
    SMC_R_NO_ERROR_TO_RESET = 120,
    SMC_R_DRIVE_DOESNT_ANSWER = 121,
    SMC_R_ERROR_NOT_RESETTABLE = 122,
    SMC_R_DRIVE_DOESNT_ANSWER_IN_TIME = 123,
    SMC_R_CANNOT_RESET_COMMUNICATION_ERROR = 124,
    SMC_RP_PARAM_UNKNOWN = 130,
    SMC_RP_REQUESTING_ERROR = 131,
    SMC_RP_DRIVE_PARAMETER_NOT_MAPPED = 132,
    SMC_RP_PARAM_CONVERSION_ERROR = 133,
    SMC_WP_PARAM_INVALID = 140,
    SMC_WP_SENDING_ERROR = 141,
    SMC_WP_DRIVE_PARAMETER_NOT_MAPPED = 142,
    SMC_WP_PARAM_CONVERSION_ERROR = 143,
    SMC_H_AXIS_WASNT_STANDSTILL = 170,
    SMC_H_AXIS_DIDNT_START_HOMING = 171,
    SMC_H_AXIS_DIDNT_ANSWER = 172,
    SMC_H_ERROR_WHEN_STOPPING = 173,
    SMC_H_AXIS_IN_ERRORSTOP = 174,
    SMC_MS_UNKNOWN_STOPPING_ERROR = 180,
    SMC_MS_INVALID_ACCDEC_VALUES = 181,
    SMC_MS_DIRECTION_NOT_APPLICABLE = 182,
    SMC_MS_AXIS_IN_ERRORSTOP = 183,
    SMC_BLOCKING_MC_STOP_WASNT_CALLED = 184,
    SMC_MS_AXIS_ALREADY_STOPPING = 185,
    SMC_UNKNOWN_TASK_INTERVAL = 200,
    SMC_MA_INVALID_VELACC_VALUES = 201,
    SMC_MA_INVALID_DIRECTION = 202,
    SMC_MR_INVALID_VELACC_VALUES = 226,
    SMC_MR_INVALID_DIRECTION = 227,
    SMC_OVR_INVALID_OVERRIDE_FACTORS = 231,
    SMC_MAD_INVALID_VELACC_VALUES = 251,
    SMC_MAD_INVALID_DIRECTION = 252,
    SMC_MSI_INVALID_VELACC_VALUES = 276,
    SMC_MSI_INVALID_DIRECTION = 277,
    SMC_MSI_INVALID_EXECUTION_ORDER = 278,
    SMC_LOGICAL_NO_REAL_AXIS = 300,
    SMC_MV_INVALID_ACCDEC_VALUES = 301,
    SMC_MV_DIRECTION_NOT_APPLICABLE = 302,
    SMC_PP_ARRAYSIZE = 325,
    SMC_PP_STEP0MS = 326,
    SMC_VP_ARRAYSIZE = 350,
    SMC_VP_STEP0MS = 351,
    SMC_AP_ARRAYSIZE = 375,
    SMC_AP_STEP0MS = 376,
    SMC_TP_TRIGGEROCCUPIED = 400,
    SMC_TP_COULDNT_SET_WINDOW = 401,
    SMC_TP_COMM_ERROR = 402,
    SMC_TRIGGER_OUT_OF_RANGE = 403,
    SMC_LATCH_IN_CONTROLLER_NOT_SUPPORTED = 404,
    SMC_AT_TRIGGERNOTOCCUPIED = 410,
    SMC_MCR_INVALID_VELACC_VALUES = 426,
    SMC_MCR_INVALID_DIRECTION = 427,
    SMC_MCA_INVALID_VELACC_VALUES = 451,
    SMC_MCA_INVALID_DIRECTION = 452,
    SMC_MCA_DIRECTION_NOT_APPLICABLE = 453,
    SMC_SDL_INVALID_AXIS_STATE = 475,
    SMC_SDL_INVALID_VELACC_VALUES = 476,
    SMC_SACF_INVALID_DYNAMIC_FACTOR = 480,
    SMC_CR_NO_TAPPETS_IN_CAM = 600,
    SMC_CR_TOO_MANY_TAPPETS = 601,
    SMC_CR_MORE_THAN_32_ACCESSES = 602,
    SMC_CI_NO_CAM_SELECTED = 625,
    SMC_CI_MASTER_OUT_OF_SCALE = 626,
    SMC_CI_RAMPIN_NEEDS_VELACC_VALUES = 627,
    SMC_CI_SCALING_INCORRECT = 628,
    SMC_CI_TOO_MANY_TAPPETS_PER_CYCLE = 629,
    SMC_CI_MORE_THAN_32_ACCESSES = 630,
    SMC_CB_NOT_IMPLEMENTED = 640,
    SMC_GI_RATIO_DENOM = 675,
    SMC_GI_INVALID_ACC = 676,
    SMC_GI_INVALID_DEC = 677,
    SMC_GI_MASTER_REGULATOR_CHANGED = 678,
    SMC_GI_INVALID_JERK = 679,
    SMC_PH_INVALID_VELACCDEC = 725,
    SMC_PH_ROTARYAXIS_PERIOD0 = 726,
    SMC_NO_CAM_REF_TYPE = 750,
    SMC_CAM_TABLE_DOES_NOT_COVER_MASTER_SCALE = 751,
    SMC_CAM_TABLE_EMPTY_MASTER_RANGE = 752,
    SMC_CAM_TABLE_INVALID_MASTER_MINMAX = 753,
    SMC_CAM_TABLE_INVALID_SLAVE_MINMAX = 754,
    SMC_CAM_INVALID_ELEMENT_COUNT = 755,
    SMC_GIP_MASTER_DIRECTION_CHANGE = 775,
    SMC_GIP_SLAVE_REVERSAL_CANNOT_BE_AVOIDED = 776,
    SMC_GIP_AVOID_REVERSAL_FOR_FINITE_AXIS = 777,
    SMC_GIP_MASTERSTARTDISTANCE_MUST_BE_ZERO_BUFFERED = 778,
    SMC_GIP_CANNOT_START_SYNC = 779,
    SMC_BC_BL_TOO_BIG = 800,
    SMC_QPROF_DIVERGES = 825,
    SMC_QPROF_INVALID_PARAMETER = 826,
    SMC_QPROF_NO_RESULT = 827,
    SMC_QPROF_INVALID_NEW_LBD = 828,
    SMC_QPROF_BAD_NEGOTIATION = 829,
    SMC_QPROF_INVALID_INTERVAL = 830,
    SMC_QPROF_NOT_ENOUGH_PHASES = 831,
    SMC_TG_INTERNAL_ERROR = 832,
    SMC_SRT_NOT_STANDSTILL_OR_POWEROFF = 850,
    SMC_SRT_INVALID_RAMPTYPE = 851,
    SMC_SMT_NOT_STANDSTILL_OR_POWEROFF = 852,
    SMC_SMT_INVALID_MOVEMENTTYPE_OR_POSITIONPERIOD = 853,
    SMC_SMT_AXIS_NOT_VIRTUAL = 854,
    SMC_NO_LICENSE = 1000,
    SMC_INT_VEL_ZERO = 1001,
    SMC_INT_NO_STOP_AT_END = 1002,
    SMC_INT_DATA_UNDERRUN = 1003,
    SMC_INT_VEL_NONZERO_AT_STOP = 1004,
    SMC_INT_TOO_MANY_RECURSIONS = 1005,
    SMC_INT_NO_CHECKVELOCITIES = 1006,
    SMC_INT_PATH_EXCEEDED = 1007,
    SMC_INT_VEL_ACC_DEC_ZERO = 1008,
    SMC_INT_DWIPOTIME_ZERO = 1009,
    SMC_INT_JERK_NONPOSITIVE = 1010,
    SMC_INT_QPROF_DIVERGES = 1011,
    SMC_INT_INVLALID_VELOCITY_MODE = 1012,
    SMC_INT_TOO_MANY_AXES_INTERPOLATED = 1013,
    SMC_INT_DEGENERATE_SEGMENT = 1014,
    SMC_HIGH_CURVATURE_SPLINE = 1015,
    SMC_INT2DIR_BUFFER_TOO_SMALL = 1050,
    SMC_INT2DIR_PATH_FITS_NOT_IN_QUEUE = 1051,
    SMC_XINT_INVALID_DIRECTION = 1070,
    SMC_XINT_NOINTERSECTION = 1071,
    SMC_WAR_INT_OUTQUEUE_TOO_SMALL = 1080,
    SMC_WAR_END_VELOCITIES_INCORRECT = 1081,
    SMC_CV_ACC_DEC_VEL_NONPOSITIVE = 1100,
    SMC_CA_INVALID_ACCDEC_VALUES = 1120,
    SMC_TOK_INCOMPLETE_TOKEN_AT_END_OF_INPUT = 1130,
    SMC_TOK_NOT_A_VALID_TOKEN = 1131,
    SMC_TOK_AMBIGUOUS_INPUT = 1132,
    SMC_TOK_STRING_TOO_LONG_FOR_TOKEN = 1133,
    SMC_TOK_INVALID_NUMLIT = 1134,
    SMC_PRS_FUNC_DECL_TOO_FEW_ARGUMENTS = 1150,
    SMC_PRS_FUNC_DECL_TOO_MANY_ARGUMENTS = 1151,
    SMC_PRS_FUNC_DECL_WRONG_ARGUMENT_TYPE = 1152,
    SMC_PRS_LOCAL_VAR_NOT_FOUND = 1153,
    SMC_PRS_INVALID_STRING = 1154,
    SMC_PRS_TOO_MANY_CLOSING_BRACKETS = 1155,
    SMC_PRS_TOO_MANY_OPENING_BRACKETS = 1156,
    SMC_PRS_NO_SUCH_INFIX_OPERATOR = 1157,
    SMC_PRS_NO_SUCH_PREFIX_OPERATOR = 1158,
    SMC_PRS_OPERATOR_INVALID_PRECEDENCE = 1159,
    SMC_PRS_NOT_A_TERM = 1160,
    SMC_PRS_EXPRESSION_INVALID_SEQUENCE = 1161,
    SMC_PRS_TOO_MANY_TERMS = 1162,
    SMC_PRS_STACK_OVERFLOW = 1163,
    SMC_PRS_VAR_NAME_ALREADY_USED = 1164,
    SMC_PRS_INCOMPLETE_SENTENCE_IN_TOKEN_QUEUE = 1165,
    SMC_PRS_TOO_MANY_SUBPROGRAMS = 1167,
    SMC_PRS_TOO_MANY_SUBPROGRAM_PARAMETERS = 1168,
    SMC_PRS_SUBPROGRAM_LOOKUP_FAILED = 1169,
    SMC_PRS_VAR_NOT_FOUND = 1170,
    SMC_PRS_TOKEN_TYPE_UNKNOWN = 1171,
    SMC_PRS_GOT_NO_TERM = 1172,
    SMC_PRS_INVALID_VAR_TYPE = 1173,
    SMC_PRS_UNEXPECTED_TOKEN = 1174,
    SMC_PRS_ID3_EXPECTED = 1175,
    SMC_PRS_ID_TOO_LONG = 1176,
    SMC_PRS_GADDRESS_EXPECTED = 1177,
    SMC_PRS_NWORD_EXPECTED = 1178,
    SMC_PRS_NWORD_INVALID_SENTENCE_NUMBER = 1179,
    SMC_PRS_NWORD_SENTENCE_NUMBER_NO_NUMBER_LITERAL = 1180,
    SMC_PRS_USE_OF_RESERVED_KEYWORD = 1181,
    SMC_PRS_SUBPROGRAMS_SIGNATURE_MISMATCH = 1182,
    SMC_PRS_INITIAL_VALUE_HAS_WRONG_TYPE = 1183,
    SMC_PRS_TOO_MANY_LOCAL_VARIABLES = 1184,
    SMC_PRS_SUBPROG_MUST_BE_FIRST_SENTENCE = 1185,
    SMC_PRS_ONLY_ONE_SUBPROGRAM_PER_FILE_ALLOWED = 1186,
    SMC_PRS_LET_AFTER_REGULAR_SENTENCE = 1187,
    SMC_PRS_UNMATCHED_END_SUBPROGRAM = 1188,
    SMC_PRS_UNEXPECTED_TOKENS_AFTER_SUBPROGRAM = 1189,
    SMC_PRS_MISSING_END_SUBPROGRAM = 1190,
    SMC_PRS_USE_OF_KEYWORD = 1191,
    SMC_PRS_DYNCALL_EXPECTED_SUBNAME_EXP = 1192,
    SMC_PRS_DYNCALL_EXPECTED_SUBNAME_TYPE_STRING = 1193,
    SMC_DEC_ACC_TOO_LITTLE = 1200,
    SMC_DEC_RET_TOO_LITTLE = 1201,
    SMC_DEC_OUTQUEUE_RAN_EMPTY = 1202,
    SMC_DEC_JUMP_TO_UNKNOWN_LINE = 1203,
    SMC_DEC_INVALID_SYNTAX = 1204,
    SMC_DEC_3DMODE_OBJECT_NOT_SUPPORTED = 1205,
    SMC_DEC_NEGATIVE_PERIOD = 1206,
    SMC_DEC_DIMENSIONS_EXCLUSIVE_AU = 1207,
    SMC_DEC_DIMENSIONS_EXCLUSIVE_BV = 1208,
    SMC_DEC_DIMENSIONS_EXCLUSIVE_CW = 1209,
    SMC_DEC_DCS_NOT_ALL_OF_ABC_GIVEN = 1210,
    SMC_DEC_DCS_2D_NOT_IN_XY_PLANE = 1211,
    SMC_DEC_CIRCLE_NON_UNIFORM_SCALING = 1212,
    SMC_DEC_ROTATION_AFFECTS_SCALING = 1213,
    SMC_DEC_DCS_NOT_ALL_OF_IJK_GIVEN = 1214,
    SMC_IPR_LOCAL_VAR_UNKNOWN_TYPE = 1250,
    SMC_IPR_LVALUE_WRONG_TYPE = 1251,
    SMC_IPR_EVAL_STACK_OVERFLOW = 1252,
    SMC_IPR_NOT_A_NUMBER = 1253,
    SMC_IPR_DIVISION_BY_ZERO = 1254,
    SMC_IPR_INVALID_SCALING_FACTORS = 1255,
    SMC_IPR_INTERPRETER_STACK_IMBALANCE = 1256,
    SMC_IPR_INTERPRETER_STACK_OVERFLOW = 1257,
    SMC_IPR_INVALID_INTERPRETER_STACK_BUFFER = 1258,
    SMC_IPR_BUFFER_TOO_SMALL = 1259,
    SMC_DNCCS_NO_DATA = 1280,
    SMC_DNCCS_TOO_MANY_CALLSTACKS = 1281,
    SMC_DNCCS_INVALID_PROGRAM_INDEX = 1282,
    SMC_DNCCS_TOO_MANY_PROGRAMS = 1283,
    SMC_DNCCS_WRONG_TASK = 1284,
    SMC_GCV_BUFFER_TOO_SMALL = 1300,
    SMC_GCV_BUFFER_WRONG_TYPE = 1301,
    SMC_GCV_UNKNOWN_IPO_LINE = 1302,
    SMC_CNC_INTERNAL_ERROR = 1400,
    SMC_PATH_MAX_HPOINTS_EXCEEDED = 1401,
    SMC_TRC_G75_NOT_ALLOWED = 1410,
    SMC_TRC_QUEUE_FULL_NON_CARTESIAN = 1411,
    SMC_TRC_SPLINE3D_5_NOT_SUPPORTED = 1412,
    SMC_TRC_PLANE_CHANGE_NOT_ALLOWED = 1414,
    SMC_CNC_INVALID_GEOINFO = 1415,
    SMC_CNC_CANNOT_APPEND_TO_OUTQUEUE = 1416,
    SMC_NAV_MAX_SUBPROGRAM_NESTING_EXCEEDED = 1450,
    SMC_NAV_RETURN_FROM_MAIN = 1451,
    SMC_NAV_SUBPROGRAM_DECLARATION_NOT_FOUND = 1452,
    SMC_NAV_NOT_ENOUGH_SPACE_FOR_COMPLETE_SENTENCE = 1453,
    SMC_NO_CNC_REF_TYPE = 1500,
    SMC_NO_OUTQUEUE_TYPE = 1501,
    SMC_GEOINFO_BUFFER_MISALIGNED = 1502,
    SMC_3D_MODE_NOT_SUPPORTED = 1600,
    SMC_SAA_SMOOTHAREA_TOO_LARGE = 1700,
    SMC_SAA_SP_INVALID_INPUT = 1701,
    SMC_SA_QUEUE_NOT_IN_BUFFER = 1800,
    SMC_SA_QUEUE_CHANGED_DURING_OP = 1801,
    SMC_OS_INVALID_PARAMETER = 1820,
    SMC_BSSP_IPO_NOT_ACTIVE = 1830,
    SMC_BS_SAVEDPOS_NOT_REACHED = 1831,
    SMC_BS_NO_POS_STORED = 1832,
    SMC_INVALID_FEATURE_FLAG = 1900,
    SMC_SMB_HFUN_NOT_SUPPORTED = 1901,
    SMC_SMB_ONLY_3DMODE = 1902,
    SMC_SMB_ERROR_COMPUTING_SPLINE = 1903,
    SMC_SMM_INVALID_PARAM_NUMBER = 1910,
    SMC_INVALID_PARAMETER = 1950,
    SMC_BLENDING_NOT_SUPPORTED_BY_PREVIOUS_MOVEMENT = 1951,
    SMC_BUFFERED_NOT_SUPPORTED_BY_PREVIOUS_MOVEMENT = 1952,
    SMC_INHERIT_OWNER_ACTIVE_MOVEMENT_NOT_CALLED = 1953,
    SMC_MOVING_WITHOUT_ACTIVE_MOVEMENT = 1954,
    SMC_BUFFER_MODE_NOT_SUPPORTED = 1955,
    SMC_ERROR_IN_A_PREVIOUS_MOVEMENT = 1956,
    SMC_MORE_THAN_ONE_MOVEMENT_PER_INSTANCE = 1957,
    SMC_RNCF_FILE_DOESNT_EXIST = 2000,
    SMC_RNCF_NO_BUFFER = 2001,
    SMC_RNCF_BUFFER_TOO_SMALL = 2002,
    SMC_RNCF_DATA_UNDERRUN = 2003,
    SMC_RNCF_VAR_COULDNT_BE_REPLACED = 2004,
    SMC_RNCF_NOT_VARLIST = 2005,
    SMC_RNCF_NO_STRINGBUFFER = 2006,
    SMC_RNCF_STRINGBUFFER_OVERRUN = 2007,
    SMC_RNCF_SUBPROGRAM_FILE_NOT_FOUND = 2008,
    SMC_RNCF_FILE_CANNOT_DETERMINE_SIZE = 2009,
    SMC_RNCQ_FILE_DOESNT_EXIST = 2050,
    SMC_RNCQ_NO_BUFFER = 2051,
    SMC_RNCQ_BUFFER_TOO_SMALL = 2052,
    SMC_RNCQ_UNEXPECTED_EOF = 2053,
    SMC_ADL_FILE_CANNOT_BE_OPENED = 2100,
    SMC_ADL_BUFFER_OVERRUN = 2101,
    SMC_RCAM_FILE_DOESNT_EXIST = 2200,
    SMC_RCAM_TOO_MUCH_DATA = 2201,
    SMC_RCAM_WRONG_COMPILE_TYPE = 2202,
    SMC_RCAM_WRONG_VERSION = 2203,
    SMC_RCAM_UNEXPECTED_EOF = 2204,
    SMC_WDPF_CHANNEL_OCCUPIED = 3001,
    SMC_WDPF_CANNOT_CREATE_FILE = 3002,
    SMC_WDPF_ERROR_WHEN_READING_PARAMS = 3003,
    SMC_WDPF_TIMEOUT_PREPARING_LIST = 3004,
    SMC_ENC_DENOM_ZERO = 5000,
    SMC_ENC_AXISUSEDBYOTHERFB = 5001,
    SMC_ENC_FILTER_DEPTH_INVALID = 5002,
    SMC_INTERNAL_ERROR_INIT_MOVEMENT = 6000,
    SMC_INVALID_AXIS_TYPE = 6001,
    SMC_PCCQ_POINTBUFFERTOOSMALL = 10000,
    SMC_PCCQ_INPUTBUFFERFULLBUTNOTFINALIZED = 10001,
    SMC_AXIS_GROUP_WRONG_STATE = 11000,
    SMC_AXIS_GROUP_TOO_MANY_AXES = 11001,
    SMC_AXIS_GROUP_INVALID_DYNLIMITS = 11002,
    SMC_AXIS_GROUP_INVALID_COORD_SYSTEM = 11004,
    SMC_AXIS_GROUP_SINGLE_AXIS_ERROR = 11005,
    SMC_MOVE_INVALID_BUFFER_MODE = 11006,
    SMC_MOVE_INVALID_DYNAMIC_FACTOR = 11007,
    SMC_MOVE_INVALID_DYNAMICS = 11008,
    SMC_AXIS_GROUP_AXIS_NOT_PART_OF_GROUP = 11009,
    SMC_AXIS_GROUP_NOT_SUPPORTED = 11010,
    SMC_AXIS_GROUP_KINEMATICS_NOT_SET = 11011,
    SMC_AXIS_GROUP_WRONG_NUMBER_OF_AXES = 11012,
    SMC_AXIS_GROUP_INTERRUPTED_BY_SINGLE_AXIS = 11013,
    SMC_AXIS_GROUP_FOLLOW_SETVALUES = 11014,
    SMC_AXIS_GROUP_TOO_MANY_DEPENDENCIES = 11015,
    SMC_AXIS_GROUP_MUTUAL_DEPENDENCY = 11016,
    SMC_AXIS_GROUP_DEPENDENCY_IN_DIFFERENT_TASK = 11017,
    SMC_AXIS_GROUP_AXIS_IN_DIFFERENT_TASK = 11018,
    SMC_AXIS_GROUP_PCS_STILL_IN_USE = 11019,
    SMC_AXIS_GROUP_CMD_ABORTED_DUE_TO_ERROR = 11020,
    SMC_AXIS_GROUP_INVALID_PARAMETER = 11021,
    SMC_AXIS_GROUP_UNSUPPORTED_RAMPTYPE = 11022,
    SMC_MOVE_INVALID_TRANSITION_PARAMETER = 11023,
    SMC_AXIS_GROUP_CPTR_CANNOT_FOLLOW = 11025,
    SMC_AXIS_GROUP_CONTINUE_WRONG_POSITION = 11026,
    SMC_AXIS_GROUP_CONTINUE_BUFFER_TOO_SMALL = 11027,
    SMC_AXIS_GROUP_CONTINUE_WRONG_CHECKSUM = 11028,
    SMC_AXIS_GROUP_IDLE_WAIT_AXES_MOVING = 11029,
    SMC_AXIS_INVERSE_TRAFO_EXCEEDING_POSLIMITS = 11030,
    SMC_AXIS_GROUP_CANNOT_ADD_SAME_AXIS = 11031,
    SMC_AXIS_GROUP_TRANSFORMATION_NOT_SET = 11032,
    SMC_AXIS_GROUP_NON_RESUMABLE_ERROR = 11033,
    SMC_AXIS_GROUP_CONTINUE_DATA_NOT_WRITTEN = 11034,
    SMC_AXIS_GROUP_INVALID_INTERRUPT_POSITION = 11036,
    SMC_RELATIVE_MOVEMENT_TRACKING_CS = 11037,
    SMC_RELATIVE_MOVEMENT_ABORTING_TRACKING = 11038,
    SMC_CIRCULAR_MOVEMENT_TRACKING_CS = 11039,
    SMC_CIRCULAR_MOVEMENT_ABORTING_TRACKING_CS = 11040,
    SMC_AXIS_GROUP_CONTINUE_POSITION_WRONG_CHECKSUM = 11041,
    SMC_CIRCULAR_TRACKING_TOOL_CHANGE_NOT_SUPPORTED = 11042,
    SMC_AXIS_GROUP_COULD_NOT_WRITE_CONTINUE_DATA = 11043,
    SMC_MODULO_AXIS_FOR_NON_ROTARY_JOINT = 11044,
    SMC_MODULO_AXIS_FOR_LIMITED_ROTARY_JOINT = 11045,
    SMC_MODULO_AXIS_PERIOD_NOT_360 = 11046,
    SMC_FB_WASNT_CALLED_DURING_EXECUTION = 11047,
    SMC_NO_EVALUATION_POSSIBLE_FOR_TIME_OFFSET = 11048,
    SMC_INVALID_SOURCE_TYPE_FOR_TIME_OFFSET = 11049,
    SMC_INVALID_TIME_OFFSET = 11050,
    SMC_TIME_OFFSET_TOO_LARGE = 11051,
    SMC_KERNEL_PTP_INTERNAL_ERROR = 11100,
    SMC_KERNEL_PTP_INVALID_TASKCYCLETIME = 11101,
    SMC_TRAFO_INVALID_PARAMETERS = 12000,
    SMC_TRAFO_INVALID_CONSTELLATION = 12001,
    SMC_TRAFO_INVALID_COUPLING = 12002,
    SMC_TRAFO_NOT_INITIALIZED = 12003,
    SMC_TRAFO_NO_TOOL_WITH_OFFSET_ALLOWED = 12004,
    SMC_AXIS_GROUP_TOOL_OFFSET_INCOMPATIBLE_WITH_KINEMATICS = 12005,
    SMC_TRAFO_INVALID_AXIS_LIMITS = 12006,
    SMC_AXIS_GROUP_PATH_DEVIATION_TOO_HIGH = 12007,
    SMC_AXIS_POSITION_EXCEEDS_POSLIMITS = 12008,
    SMC_AXIS_GROUP_NO_DYNAMIC_MODEL_CONFIGURED = 12009,
    SMC_DYNAMICS_NUM_TORQUES_NEQ_NUM_AXES = 12010,
    SMC_CP_CACHE_FULL = 12100,
    SMC_CP_EVAL_ERROR = 12101,
    SMC_CP_NON_CONTINUABLE_STATE = 12102,
    SMC_CP_MAX_LENGTH_EXCEEDED = 12103,
    SMC_CP_ACCELERATION_TOO_HIGH = 12104,
    SMC_CP_MAX_ITERATIONS_EXCEEDED = 12105,
    SMC_CP_NO_TRAJECTORY = 12106,
    SMC_CP_OUT_QUEUE_FULL = 12107,
    SMC_CP_QUEUE_UNDERRUN = 12108,
    SMC_CP_INVALID_QUEUE = 12109,
    SMC_CP_BLENDING_INTERNAL_ERROR = 12110,
    SMC_CP_CIRCLE_COLLINEAR_POINTS = 12111,
    SMC_CP_CIRCLE_CENTER_NOT_ON_BISECTOR = 12112,
    SMC_CP_CIRCLE_RADIUS_ZERO = 12113,
    SMC_CP_CIRCLE_DISTANCE_LARGER_THAN_DIAMETER = 12114,
    SMC_CP_CIRCLE_START_AND_ENDPOINT_EQUAL = 12115,
    SMC_CP_BLENDING_DEGENERATE_SPLINE = 12116,
    SMC_CP_ELEMENT_TOO_SHORT = 12117,
    SMC_CP_COULD_NOT_CUT_PATH = 12118,
    SMC_CP_INVALID_ANGULAR_VEL_ACC = 12119,
    SMC_CP_INVALID_ORIENTATION = 12120,
    SMC_CP_TIME_BUDGET_EXCEEDED = 12121,
    SMC_AXIS_GROUP_AXIS_LIMIT_VIOLATED = 12122,
    SMC_CP_CONFIGS_DIFFER = 12125,
    SMC_CP_BUS_TASK_NOT_CALLED = 12126,
    SMC_CP_NO_ROOT_IN_INTERVAL_FOUND = 12127,
    SMC_CP_KIN_DOES_NOT_SUPPORT_AXIS_ORIENTATION_IPO = 12128,
    SMC_CP_AXIS_ORIENTATION_IPO_NOT_SUPPORTED_FOR_CPTR = 12129,
    SMC_CP_INVALID_PATH_ELEM = 12130,
    SMC_CP_TRANSITION_NOT_SMOOTH = 12131,
    SMC_CP_AXIS_ORIENTATION_IPO_CONFIG_DIFFERS = 12132,
    SMC_CP_AXIS_ORIENTATION_IPO_OFFSET2_NOT_IMPLEMENTED = 12133,
    SMC_CP_ROTARY_AXIS_PERIOD_MISMATCH = 12134,
    SMC_CP_ROTARY_AXIS_RANGE_VIOLATION = 12135,
    SMC_CP_COMPUTE_TARGET_DISCONTINUITY = 12136,
    SMC_CP_TRAJECTORY_NOT_SMOOTH = 12137,
    SMC_CP_ERROR_CREATING_PARAM_TRANSFORM = 12138,
    SMC_CP_PTP_DATA_NUMBER_OF_AXES = 12139,
    SMC_CP_NEGATIVE_PATH_VELOCITY = 12140,
    SMC_CP_TRANSITIONING_FROM_SINGLE_AXIS_MOVEMENT_NOT_SUPPORTED = 12141,
    SMC_CP_PLANNER_NO_PROGRESS = 12142,
    SMC_CP_INTERNAL_EVAL_CACHE_ERROR = 12143,
    SMC_CP_INVALID_ROOT_ACC_TOO_HIGH = 12144,
    SMC_CP_INVALID_ROOT_TRAJECTORY_TOO_LARGE = 12145,
    SMC_CP_EMPTY_TRAJECTORY = 12146,
    SMC_CP_FORECAST_TOO_LARGE = 12147,
    SMC_GROUPJOG2_MAX_DISTANCE_NON_POSITIVE = 12200,
    SMC_GROUPJOG2_DYNAMIC_CS_NOT_SUPPORTED = 12201,
    SMC_TRIGGER_TOO_MANY_TRIGGERS_PREPARED = 12300,
    SMC_TRIGGER_UNSUPPORTED_MOVEMENT_TYPE = 12301,
    SMC_TRIGGER_INVALID_POS_TYPE = 12302,
    SMC_TRIGGER_RELATIVE_POSITION_OUT_OF_RANGE = 12303,
    SMC_TRIGGER_PLANE_NORMAL_NOT_A_UNIT = 12304,
    SMC_TRIGGER_PLANE_DISTANCE_NEGATIVE = 12305,
    SMC_TRIGGER_PLANE_COORD_SYSTEM_INVALID = 12306,
    SMC_TRIGGER_DISTANCE_OUT_OF_RANGE = 12307,
    SMC_TRIGGER_PLANE_NO_INTERSECTION = 12308,
    SMC_TRIGGER_TRACKING_TRANSITION_NOT_SUPPORTED = 12309,
    SMC_TRIGGER_PTP_NOT_SUPPORTED = 12310,
    SMC_FIRST_INTERNAL_ERROR_CODE = 13000,
    SMC_MOVEMENT_INTERNAL_ERROR = 13001,
    SMC_MOVEMENT_GET_POS_INTERNAL_ERROR = 13002,
    SMC_CPTR_INTERNAL_ERROR = 13003,
    SMC_CP_IPO_INTERNAL_ERROR = 13004,
    SMC_CP_ADD_NEW_MOVEMENT_INTERNAL_ERROR = 13005,
    SMC_AXIS_GROUP_COORDINATION_INTERNAL_ERROR = 13006,
    SMC_AXIS_GROUP_ADD_MOVEMENT_INTERNAL_ERROR = 13007,
    SMC_AXIS_GROUP_READ_AXIS_STATES_INTERNAL_ERROR = 13008,
    SMC_AXIS_GROUP_READ_VEL_INTERNAL_ERROR = 13009,
    SMC_AXIS_GROUP_READ_ACC_INTERNAL_ERROR = 13010,
    SMC_AXIS_GROUP_INVALID_STATE_INTERNAL_ERROR = 13011,
    SMC_AXIS_GROUP_PCS_INTERNAL_ERROR = 13012,
    SMC_AXIS_GROUP_INTERRUPT_INTERNAL_ERROR = 13013,
    SMC_CONTINUE_DATA_READ_INTERNAL_ERROR = 13014,
    SMC_CONTINUE_DATA_WRITE_INTERNAL_ERROR = 13015,
    SMC_PATH_ELEM_INTERNAL_ERROR = 13016,
    SMC_PATH_ELEM_ESTIMATE_LIMITS_INTERNAL_ERROR = 13017,
    SMC_PATH_ELEM_ZERO_LEN_INTERNAL_ERROR = 13018,
    SMC_PATH_ELEM_BLEND_INTERNAL_ERROR = 13019,
    SMC_PATH_ELEM_BLEND_GEO_INTERNAL_ERROR = 13020,
    SMC_PATH_ELEM_BLEND_ORI_INTERNAL_ERROR = 13021,
    SMC_PATH_ELEM_BLEND_AS_INTERNAL_ERROR = 13022,
    SMC_ELEM_FUN_CART_INTERNAL_ERROR = 13023,
    SMC_CP_HALT_STOP_INTERNAL_ERROR = 13024,
    SMC_TRJ_PLANNING_INIT_INTERNAL_ERROR = 13025,
    SMC_TRJ_PLANNING_GEN_SAMPLES_INTERNAL_ERROR = 13026,
    SMC_TRJ_PLANNING_PATH_OUT_INTERNAL_ERROR = 13027,
    SMC_TRJ_PLANNING_EVAL_AXIS_INTERNAL_ERROR = 13028,
    SMC_TRJ_PLANNING_LOOKAHEAD_INTERNAL_ERROR = 13029,
    SMC_AXIS_GROUP_READ_JERK_INTERNAL_ERROR = 13030,
    SMC_AXIS_GROUP_WRITE_CONTINUE_POS_INTERNAL_ERROR = 13031,
    SMC_CP_TRANSITION_CHECK_FAILED = 13032,
    SMC_ABORTING_INTERNAL_ERROR = 13033,
    SMC_LINE_TO_REL_STANDSTILL_INTERNAL_ERROR = 13034,
    SMC_PATH_ELEM_POSE_EVAL_INTERNAL_ERROR = 13035,
    SMC_CS_REF_COUNT_INTERNAL_ERROR = 13036,
    SMC_PATH_QUEUE_INTERNAL_ERROR = 13037,
    SMC_PATH_ELEM_QUEUE_INTERNAL_ERROR = 13038,
    SMC_ELEM_FUN_QUEUE_INTERNAL_ERROR = 13039,
    SMC_MAC_DUPLICATE_CALLER_INTERNAL_ERROR = 13040,
    SMC_MAC_INTERNAL_ERROR = 13041,
    SMC_READ_POSITION_INTERNAL_ERROR = 13042,
    SMC_ELEM_FUN_PROJECT_POINT_INTERNAL_ERROR = 13043,
    SMC_LAST_INTERNAL_ERROR_CODE = 13999,
}
export interface AxisSimpleSts {
    activeStreamType: number;
    actualAcceleration: number;
    actualControllerMode: number;
    actualCurrent: number;
    actualMasterAxisDevId: number;
    actualPosition: number;
    actualTorque: number;
    actualVelocity: number;
    atHomePosition: boolean;
    atOperationalPositionMax: boolean;
    atOperationalPositionMin: boolean;
    axesPositionDifference_CORRECTABLE: boolean;
    axesPositionDifference_OK: boolean;
    calculatedStoppingPosition: number;
    configuredSoftLimitTravelRange: number;
    driveHasError: boolean;
    driveHwLimitsEnforcement: AxisLimitEnforcements;
    driveIsStoppingMotor: boolean;
    driveState: number;
    driveStatusMsg: string;
    driveStoppedMotor: boolean;
    driveSwLimitsEnforcement: AxisLimitEnforcements;
    dualAxisStopType: DualAxisStopTypes;
    etherCatComms_OK: boolean;
    homeOffsetFromZero: number;
    ignoringRailBrakes: boolean;
    interlocks: AxisInterlocks;
    isAtPosAndStandstill: boolean;
    isEnabled: boolean;
    isGeared: boolean;
    isHomed: boolean;
    isHoming: boolean;
    isJogging: boolean;
    isMastered: boolean;
    isMoving: boolean;
    isStandstill: boolean;
    isStreaming: boolean;
    isTorquing: boolean;
    mutingSwAndHwLimitsWhileHoming: boolean;
    permissives: Array<AxisPermissiveStsData>;
    positionDifference: number;
    railBrakes: RailBrakeInputs;
    recordedPosition: number;
    restrictedToSlow: boolean;
    sensors: Array<boolean>;
    setAccel: number;
    setJerk: number;
    setPosition: number;
    setTorque: number;
    setVelocity: number;
    skippingPositionCorrectionBeforeGearing: boolean;
    softMotionErrorId: SM3ErrorSMCERROR;
    softMotionHasError: boolean;
    targetControllerMode: number;
    targetDir: number;
    targetEncoderSetpoint: number;
    targetMasterAxisDevId: number;
    targetMaxCurrent: number;
    targetMotionProfileData: AxisMotionProfileData;
    targetMotionProfileId: number;
    targetPosition: number;
    targetSetpoint: number;
    targetTorque: number;
    targetVelocity: number;
    travelLimitNegative: number;
    travelLimitPositive: number;
}
export interface SysCfg {
    placeholder: boolean;
}
export interface SysSts {
    placeholder: boolean;
}
export interface TaskData {
    description: string;
    paramArray: Array<number>;
    state: number;
    targetId: number;
    taskId: number;
}
export interface TaskQueue {
    activeTaskIndex: number;
    taskCnt: number;
    taskList: Array<TaskData>;
    topPriority: number;
}
export interface UdpInterfaceCfg {
    last3DigitsOfIpcIpAddr: number;
    listenPort: number;
    targetIpAddress: string;
    targetPort: number;
}
export interface UdpCfg {
    deviceIdArray: Array<number>;
    heartbeatTimeoutSec: number;
    udpStatusDataSchemaVersion: number;
    updInterfaceCfg: UdpInterfaceCfg;
}
export interface UdpSts {
    incomingDataIsRecent: boolean;
    udpPeerIsRunning: boolean;
}
export interface ExtServiceCfg {
    triggerErrorIfLostHeartbeat: boolean;
}
export interface VisMeta {
    flipBit: boolean;
    recordingFilenameMetaData: string;
    recordingFolderPath: string;
}
export interface CameraStatus {
    isConnected: boolean;
    isPluggedIn: boolean;
    isStreaming: boolean;
    recordingState: number;
    videoDeviceNodeString: string;
}
export interface CameraCfg {
    id: number;
    serialNumber: string;
    streamingPort: number;
}
export interface VisCfg {
    autoConnect: boolean;
    autoStream: boolean;
    cameraCfgs: Array<CameraCfg>;
    numCameras: number;
}
export interface IExtServiceInputs {
    activeTaskId: number;
    errorId: number;
    flipBit: boolean;
    heartbeatVal: number;
    lastTaskId: number;
    stepNum: number;
    taskStepNum: number;
    uniqueTaskActiveId: number;
}
export interface IExtServiceOutputs {
    deviceCmdReqId: number;
    execMethodReqId: number;
    heartbeatVal: number;
    taskParam0: number;
    taskParam1: number;
    taskParam2: number;
    taskParam3: number;
    taskReqId: number;
    uniqueTaskReqId: number;
}
export interface IExtService {
    i: IExtServiceInputs;
    o: IExtServiceOutputs;
}
export interface VisSts {
    allDisconnected: boolean;
    cameraStates: Array<CameraStatus>;
    cfg: VisCfg;
    extServiceCfg: ExtServiceCfg;
    iExtService: IExtService;
    isConnected: boolean;
    isRecording: boolean;
    pluggedInSerialNumbers: Array<string>;
}

export type Machine = {
    abbCfg: RctrlCfg;
    abbHmiManual: RctrlHmiManual;
    abbSts: RctrlSts;
    activeRecipe: RecipeData;
    clamp_sCfg: TwoPosCfg;
    clamp_sSts: TwoPosSts;
    clamp_tCfg: TwoPosCfg;
    clamp_tSts: TwoPosSts;
    conCfg: ConCfg;
    conSts: ConSts;
    devicesIds_00251: DeviceIds;
    eoatCfg: TwoPosCfg;
    eoatSts: TwoPosSts;
    fix_sCfg: TwoPosGantryCfg;
    fix_sSts: TwoPosGantrySts;
    fix_tCfg: TwoPosGantryCfg;
    fix_tSts: TwoPosGantrySts;
    flsb_sCfg: TwoPosCfg;
    flsb_sSts: TwoPosSts;
    flsb_tCfg: TwoPosCfg;
    flsb_tSts: TwoPosSts;
    gripCfg: TwoPosCfg;
    gripSts: TwoPosSts;
    hmiCfg: HmiCfg;
    hmiSts: HmiSts;
    inputs: inputs;
    job: JobData;
    outputs: outputs;
    pdmSts: PartDataStatus;
    potCfg: PotCfg;
    potSts: PotSts;
    recipeStore: RecipeStore;
    robCfg: RobCfg;
    robMeta: RobMeta;
    robSts: RobSts;
    sftyCfg: SftyCfg;
    sftySts: SftySts;
    squeeCfg: AxisCfg;
    squeeSts: AxisSimpleSts;
    sysCfg: SysCfg;
    sysSts: SysSts;
    taskQueue: TaskQueue;
    udpCfg: UdpCfg;
    udpSts: UdpSts;
    visCfg: ExtServiceCfg;
    visMeta: VisMeta;
    visSts: VisSts;
    visStsExtService: VisSts;
};
export type MachineTypeRoot = {
    abbCfg: RctrlCfg;
    abbHmiManual: RctrlHmiManual;
    abbSts: RctrlSts;
    activeRecipe: RecipeData;
    clamp_sCfg: TwoPosCfg;
    clamp_sSts: TwoPosSts;
    clamp_tCfg: TwoPosCfg;
    clamp_tSts: TwoPosSts;
    conCfg: ConCfg;
    conSts: ConSts;
    devicesIds_00251: DeviceIds;
    eoatCfg: TwoPosCfg;
    eoatSts: TwoPosSts;
    fix_sCfg: TwoPosGantryCfg;
    fix_sSts: TwoPosGantrySts;
    fix_tCfg: TwoPosGantryCfg;
    fix_tSts: TwoPosGantrySts;
    flsb_sCfg: TwoPosCfg;
    flsb_sSts: TwoPosSts;
    flsb_tCfg: TwoPosCfg;
    flsb_tSts: TwoPosSts;
    gripCfg: TwoPosCfg;
    gripSts: TwoPosSts;
    hmiCfg: HmiCfg;
    hmiSts: HmiSts;
    inputs: inputs;
    job: JobData;
    outputs: outputs;
    pdmSts: PartDataStatus;
    potCfg: PotCfg;
    potSts: PotSts;
    recipeStore: RecipeStore;
    robCfg: RobCfg;
    robMeta: RobMeta;
    robSts: RobSts;
    sftyCfg: SftyCfg;
    sftySts: SftySts;
    squeeCfg: AxisCfg;
    squeeSts: AxisSimpleSts;
    sysCfg: SysCfg;
    sysSts: SysSts;
    taskQueue: TaskQueue;
    udpCfg: UdpCfg;
    udpSts: UdpSts;
    visCfg: ExtServiceCfg;
    visMeta: VisMeta;
    visSts: VisSts;
    visStsExtService: VisSts;
};
export type MachineRuntimeExcludedKeys = 'SyncClockReq' | 'ResetEthercat_REQ' | 'DeviceLogs' | 'RegisteredInputs' | 'Utilities' | 'RegisteredDevices' | 'Devices' | 'DeviceRegisteredActions' | 'SysFb';
export type MachineRuntime = Omit<Machine, MachineRuntimeExcludedKeys>;
export type MachineRuntimeRoot = Omit<MachineTypeRoot, MachineRuntimeExcludedKeys>;
