// This file is generated by machine-bridge/src/type-generator/generate-machine-types.ts
// Output location defaults to machine-bridge/generated-types/shared/types.ts.
// Do not edit by hand; rerun the generator against a live OPC UA server.

export const machineTypeSource = {
    "controllerName": "CODESYS Control for Linux SL",
    "endpoint": "opc.tcp://127.0.0.1:4840",
    "generatedAt": "2026-05-18T23:01:47.604Z",
    "rootNodeId": "ns=4;s=|var|CODESYS Control for Linux SL.Application.Machine_00251",
    "rootTag": "Machine_00251"
} as const;

export enum RctrlControllerTypes {
    UNKNOWN = 0,
    ABB = 1,
}
export interface AxisMotionProfileData {
    acceleration: number;
    jerk: number;
    speed: number;
}
export interface RobPositionData {
    pdeg: number;
    rdeg: number;
    toolFrameId: number;
    userFrameId: number;
    wdeg: number;
    x: number;
    y: number;
    z: number;
}
export interface CoordinateFrame {
    id: number;
    location: RobPositionData;
    name: string;
}
export interface RctrlCfg {
    AtLinearPosTol: number;
    AtRotationalPosTol: number;
    ControllerId: number;
    ControllerType: RctrlControllerTypes;
    IgnoreLimitSwitches: boolean;
    Ignores: Array<boolean>;
    IgnoreSoftwareLimits: boolean;
    LinearUnit: string;
    MotionProfiles: Array<AxisMotionProfileData>;
    Positions: Array<RobPositionData>;
    RotationalUnit: string;
    ToolFrames: Array<CoordinateFrame>;
    UserFrames: Array<CoordinateFrame>;
}
export interface ApplicatorSetpoint {
    BallValveOn: boolean;
    Speed: number;
    SqueegeeDiameter: number;
    StepperPosition: number;
    ZOffset: number;
}
export interface AbbDataOutputs {
    ApplicatorCollisionPayloadOffset: number;
    ApplicatorPreloadPauseDuration: number;
    ApplicatorSetpoints: Array<ApplicatorSetpoint>;
    ApplicatorToolId: number;
    ApplicatorToolPresent: boolean;
    BrushIsActive: boolean;
    BrushLinearSpeed: number;
    BrushToolPresent: boolean;
    CameraId: number;
    CameraSpeed: number;
    CameraToolPresent: boolean;
    CleanerId: number;
    ClearErrorsReq: boolean;
    deviceCmdReqId: number;
    DryCycle: boolean;
    EoatPickDone: boolean;
    EoatReleaseDone: boolean;
    ExecMethodReqId: number;
    FalseBottomStaysOpen: boolean;
    GripperIsClosed: boolean;
    GripperIsOpen: boolean;
    heartbeatVal: number;
    KillReq: boolean;
    PauseReq: boolean;
    PlcPartState: number;
    RecordingIsActive: boolean;
    ResetReq: boolean;
    SqueegeeAtHome: boolean;
    StartReq: boolean;
    StopReq: boolean;
    TareDone: boolean;
    TaskParam0: number;
    TaskParam1: number;
    TaskParam2: number;
    TaskParam3: number;
    TaskReqId: number;
    TransferPartDataDone: boolean;
    TubeHeightMax: number;
    TubeMassKg: number;
    TubeOuterDiameterMax: number;
    TubeTypeId: number;
    UniqueTaskReqId: number;
    UpdatePartDataDone: boolean;
    WeighingFingerId: number;
    WeighToolPresent: boolean;
    WeighTubeDone: boolean;
}
export interface RctrlHmiManual {
    AbbDataOutputs: AbbDataOutputs;
}
export interface AbbDataInputs {
    ActivePartLocationId: number;
    ActiveTaskId: number;
    ActiveToolId: number;
    ActiveToolVariantId: number;
    ActualWaypoint: number;
    AutoRecoverOK: boolean;
    AutoRecoveryNeeded: boolean;
    BrushStartReq: boolean;
    BrushStopReq: boolean;
    ControllerErrorId: number;
    EoatPickReq: boolean;
    EoatReleaseReq: boolean;
    ErrorId: number;
    GripperCloseReq: boolean;
    GripperOpenReq: boolean;
    heartbeatVal: number;
    InTransitZone: boolean;
    lastCrossedSetpointId: number;
    lastTaskId: number;
    NewPartState: number;
    RecordingStartReq: boolean;
    RecordingStopReq: boolean;
    RecoverTaskId: number;
    RecoveryTaskStepNum: number;
    RecoveryWaypointId: number;
    StartingWaypoint: number;
    StepNum: number;
    TareReq: boolean;
    TargetWaypoint: number;
    TaskStepNum: number;
    TcpPosX: number;
    TcpPosY: number;
    TcpPosZ: number;
    TcpRotP: number;
    TcpRotR: number;
    TcpRotW: number;
    TCPSpeed: number;
    TransferDataCurrentPartLocationId: number;
    TransferDataTargetPartLocationId: number;
    TransferPartDataReq: boolean;
    UniqueTaskActiveId: number;
    UpdatePartDataReq: boolean;
    WeighTubeReq: boolean;
    zOffsetFromFalseBottom: number;
}
export interface AbbSysOutputs {
    AutoOn: boolean;
    ControlOnState: boolean;
    CycleOn: boolean;
    EmergencyStop_NOT_OK: boolean;
    ExecutionError: boolean;
    LimitSpeed: number;
    MotorsOffState: boolean;
    MotorsOnState: boolean;
    RunChainOk: boolean;
}
export interface AbbInputs {
    data: AbbDataInputs;
    sysOutputs: AbbSysOutputs;
}
export interface AbbSysInputs {
    LoadAndStart: boolean;
    MotorsOff: boolean;
    MotorsOn: boolean;
    Stop: boolean;
}
export interface AbbOutputs {
    data: AbbDataOutputs;
    sysInputs: AbbSysInputs;
}
export interface AbbControllerInterface {
    i: AbbInputs;
    o: AbbOutputs;
}
export interface RctrlSts {
    ActiveToolId: number;
    ActualPosition: RobPositionData;
    ActualTCPSpeed: number;
    ActualWaypoint: number;
    Cfg: RctrlCfg;
    IController: AbbControllerInterface;
    isAtPosAndStandstill: boolean;
    IsConnected: boolean;
    isJogging: boolean;
    isMoving: boolean;
    isStandstill: boolean;
    IsTeachMode: boolean;
    RobotProgramIsCyclingInAuto: boolean;
    TargetPosition: RobPositionData;
    TargetWaypoint: number;
}
export interface RecipeData {
    ApplicatorCollisionPayloadOffset: number;
    ApplicatorHasVariableSqueegee: boolean;
    ApplicatorPreloadPauseDuration: number;
    ApplicatorSetpoints: Array<ApplicatorSetpoint>;
    ApplicatorToolId: number;
    ApplicatorToolString: string;
    BrushToolSpeed_RPM: number;
    CameraId: number;
    CameraSpeed: number;
    CameraString: string;
    CleanerId: number;
    CleanerString: string;
    dbId: string;
    FalseBottomStaysOpen: boolean;
    index: number;
    LinerPotPressure: number;
    LinerTypeString: string;
    LinerWeightMax: number;
    LinerWeightMin: number;
    MeasuredSqueegeeDiaAtSetpoint1: number;
    Nickname: string;
    RobotSpeedWhileBrushing: number;
    TubeHeightMax: number;
    TubeMassKg: number;
    TubeOuterDiameterMax: number;
    TubeTypeId: number;
    TubeTypeString: string;
    UsesBrushTool: boolean;
    WeighingFingerId: number;
    WeighingFingerString: string;
}
export enum TwoPosDeviceOutputModes {
    MAINTAINED = 0,
    AUTORESET = 1,
}
export enum TwoPosDeviceSensorModes {
    DEFAULT = 0,
    STICKY = 1,
}
export enum TwoPosValveTypes {
    UNKNOWN = 0,
    V5_3_EXHAUST = 1,
    V5_3_CLOSED = 2,
    V4_2 = 3,
    V3_2_EXHAUST = 4,
}
export interface TwoPosCfg {
    LabelA: string;
    LabelB: string;
    MissingSensA: boolean;
    MissingSensB: boolean;
    moveTimeAtoB: Date | string;
    moveTimeBtoA: Date | string;
    outputMode: TwoPosDeviceOutputModes;
    sensorMode: TwoPosDeviceSensorModes;
    solPwrNotOnEstopCircuit: boolean;
    valveType: TwoPosValveTypes;
}
export interface TwoPosSts {
    ActualPosition: number;
    AtPosA: boolean;
    AtPosB: boolean;
    Cfg: TwoPosCfg;
    overrideA: boolean;
    overrideB: boolean;
    PermA: boolean;
    PermB: boolean;
    StickyA: boolean;
    StickyB: boolean;
}
export interface TwoPosGantryPoseChildPosition {
    ChildId: number;
    PositionId: number;
}
export interface TwoPosGantryPose {
    ChildPositions: Array<TwoPosGantryPoseChildPosition>;
}
export interface TwoPosGantryCfg {
    NumAxes: number;
    Poses: Array<TwoPosGantryPose>;
    UseSimultaneousMoves: boolean;
}
export interface TwoPosGantrySts {
    ActualPosition: number;
    Cfg: TwoPosGantryCfg;
}
export interface HmiCfg {
    StartingScreen: string;
}
export enum AxisDriveTypes {
    STINGRAY = 0,
    BOSCH_FSOE = 1,
    NANOTEC = 2,
    TEKNIC = 3,
}
export enum PositionReferencingMethods {
    NONE = 0,
    HOMING = 1,
    POSITION_VERIFICATION = 2,
    HOMING_TO_HARDSTOP = 3,
}
export interface SoftMotionScalingParams {
    gearOutputTurnsLeft: number;
    gearOutputTurnsRight: number;
    incrementsLeft: number;
    invertDir: boolean;
    motorsTurnsLeft: number;
    motorTurnsRight: number;
    unitsInApplicationRight: number;
}
export enum AxisSensors {
    NONE = 0,
    HOME_SW = 1,
    NEGATIVE_LIM_SW = 2,
    POSITIVE_LIM_SW = 3,
}
export interface AxisCfg {
    AtPosTol: number;
    AutoPositionVerifyDuringReset: boolean;
    AxesPositionToleranceForSkew: number;
    AxisType: number;
    DriveId: number;
    DriveType: AxisDriveTypes;
    GearingPositionTolerance: number;
    HardStopNegative: number;
    HardStopPositive: number;
    hasDynamicNegativeLimit: boolean;
    hasDynamicPositiveLimit: boolean;
    hasRailBrakes: boolean;
    HomingToHardstopDir: number;
    IgnoreLimitSwitches: boolean;
    Ignores: Array<boolean>;
    IgnoreSoftwareLimits: boolean;
    KeepMasteredStatusAtStartup: boolean;
    MaxCurrentNormalOperation: number;
    MaxCurrentWhileHomingToHardstop: number;
    MotionProfiles: Array<AxisMotionProfileData>;
    OperationalPositionMax: number;
    OperationalPositionMin: number;
    PositionReferencingMethod: PositionReferencingMethods;
    ScaleFactorUnitsPerEncoderCount: number;
    SearchDistance: number;
    SensorPositions: Array<number>;
    ShippingPosition: number;
    SoftMotionScalingParams: SoftMotionScalingParams;
    SoftwareLimitNegative: number;
    SoftwareLimitPositive: number;
    Unit: string;
    updateScalingIsNeeded: boolean;
    ValidationSensor: AxisSensors;
    VerificationSensorOffsetFromZero: number;
}
export enum AxisLimitEnforcements {
    UNKNOWN = 0,
    ENFORCED = 1,
    UNENFORCED = 2,
}
export enum DualAxisStopTypes {
    NONE = 0,
    NORMAL = 1,
    SLAVE_FAULT = 2,
    MASTER_FAULT = 3,
}
export interface AxisInterlockCfgData {
    Description: string;
    Direction: number;
    Ignored: boolean;
    InterlockType: number;
    SenderId: number;
    TargetId: number;
}
export interface AxisInterlockStsData {
    conditionsAreMet: boolean;
    isAllowed: boolean;
    isIgnoredByCfg: boolean;
    isOverridden: boolean;
    OverridenTimeLeft: Date | string;
}
export interface AxisInterlockData {
    Cfg: AxisInterlockCfgData;
    Sts: AxisInterlockStsData;
}
export interface AxisInterlocks {
    List: Array<AxisInterlockData>;
}
export interface AxisPermissiveStsData {
    conditionsAreMet: boolean;
    isAllowed: boolean;
    isIgnoredByCfg: boolean;
    isOverridden: boolean;
}
export interface RailBrakeInputs {
    RailBrake1_CLOSED: boolean;
    RailBrake1_ERROR: boolean;
    RailBrake1_OPEN: boolean;
    RailBrake2_CLOSED: boolean;
    RailBrake2_ERROR: boolean;
    RailBrake2_OPEN: boolean;
}
export enum enumRcAxisMode {
    NONE = 0,
    STREAMING = 1,
    WAYPOINT = 2,
    TORQUEADMIT = 3,
    WAYPOINT_RELATIVE = 4,
    HOMING = 5,
}
export enum enumRcAxisHomingState {
    NONE = 0,
    NOT_HOMED = 1,
    HOMING = 2,
    HOMED = 3,
}
export enum SM3BasicSMCCONTROLLERMODE {
    SMC_NOCONTROL = 0,
    SMC_TORQUE = 1,
    SMC_VELOCITY = 2,
    SMC_POSITION = 3,
    SMC_CURRENT = 4,
}
export interface AxisSts {
    ActiveStreamType: number;
    actualAcceleration: number;
    ActualControllerMode: number;
    ActualCurrent: number;
    actualMasterAxisDevId: number;
    actualPosition: number;
    ActualTorque: number;
    actualVelocity: number;
    AxesPositionDifference_CORRECTABLE: boolean;
    AxesPositionDifference_OK: boolean;
    AxisRefState: number;
    CalculatedStoppingPosition: number;
    Cfg: AxisCfg;
    ConfiguredSoftLimitTravelRange: number;
    DriveHasError: boolean;
    DriveHwLimitsEnforcement: AxisLimitEnforcements;
    DriveIsStoppingMotor: boolean;
    DriveState: number;
    DriveStatusMsg: string;
    DriveStoppedMotor: boolean;
    DriveSwLimitsEnforcement: AxisLimitEnforcements;
    DualAxisStopType: DualAxisStopTypes;
    EtherCatComms_OK: boolean;
    HomeOffsetFromZero: number;
    ignoringRailBrakes: boolean;
    Interlocks: AxisInterlocks;
    isAtPosAndStandstill: boolean;
    isEnabled: boolean;
    isGeared: boolean;
    isHomed: boolean;
    isHoming: boolean;
    isJogging: boolean;
    isMastered: boolean;
    isMoving: boolean;
    isStandstill: boolean;
    isStreaming: boolean;
    isTorquing: boolean;
    mutingSwAndHwLimitsWhileHoming: boolean;
    Permissives: Array<AxisPermissiveStsData>;
    PositionDifference: number;
    RailBrakes: RailBrakeInputs;
    RcControlMode: enumRcAxisMode;
    RcHomingState: enumRcAxisHomingState;
    RecordedPosition: number;
    RestrictedToSlow: boolean;
    Sensors: Array<boolean>;
    setAccel: number;
    setJerk: number;
    setPosition: number;
    setTorque: number;
    setVelocity: number;
    SkippingPositionCorrectionBeforeGearing: boolean;
    SoftMotionErrorId: number;
    SoftMotionHasError: boolean;
    TargetControllerMode: SM3BasicSMCCONTROLLERMODE;
    targetDir: number;
    targetEncoderSetpoint: number;
    targetMasterAxisDevId: number;
    targetMaxCurrent: number;
    targetMotionProfileData: AxisMotionProfileData;
    targetMotionProfileId: number;
    targetPosition: number;
    targetSetpoint: number;
    targetTorque: number;
    targetVelocity: number;
    TravelLimitNegative: number;
    TravelLimitPositive: number;
}
export interface DeviceActionRequestData {
    ActionId: number;
    ActionType: number;
    ParamArray: Array<number>;
    SenderId: number;
    UniqueActionRequestId: number;
}
export interface ApiOpcuaReqData {
    ActionRequestData: DeviceActionRequestData;
    checkSum: number;
    id: number;
    Sts: number;
}
export interface ApiOpcuaData {
    HmiReq: ApiOpcuaReqData;
    HmiResp: ApiOpcuaReqData;
    InternalReq: ApiOpcuaReqData;
    InternalResp: ApiOpcuaReqData;
    OrchReq: ApiOpcuaReqData;
    OrchResp: ApiOpcuaReqData;
    Req: ApiOpcuaReqData;
    Resp: ApiOpcuaReqData;
}
export interface DeviceCfg {
    AutoReset: boolean;
    ControllableByHmi: boolean;
    Ignore: boolean;
    OutboundAxisInterlocks: Array<AxisInterlockCfgData>;
    SafetyZoneId: number;
}
export interface FaultData {
    AutoReset: boolean;
    Code: number;
    DeviceId: number;
    LogFlag: boolean;
    Msg: string;
    ParentStepNum: number;
    ResetFlag: boolean;
    StepNum: number;
    TimeStamp: bigint | number;
}
export interface DeviceFaultData {
    ChildrenPresent: boolean;
    List: Array<FaultData>;
    Present: boolean;
}
export interface ProcessData {
    ActiveId: number;
    ActiveName: string;
    DeviceStateThatCalled: number;
    DeviceStepThatCalled: number;
    firstScan: boolean;
    isDone: boolean;
    isError: boolean;
    isStepNum: number;
    LastId: number;
    NextStepNum: number;
    ParamArray: Array<number>;
    RequestId: number;
    RequestParamArray: Array<number>;
    SenderId: number;
    StepDescription: string;
    StepTime: bigint | number;
    UniqueActionRequestId: number;
}
export interface DeviceInstants {
    InstantKill_ON: boolean;
    InstantManual_ON: boolean;
    InstantReset_ON: boolean;
    InstantStop_ON: boolean;
}
export interface DeviceSts {
    Aborting: boolean;
    AllChildrenIdle: boolean;
    AllChildrenIdleOrError: boolean;
    AllChildrenInactive: boolean;
    AllChildrenKilled: boolean;
    ColorCode: number;
    CommanderId: number;
    Done: boolean;
    Error: boolean;
    Idle: boolean;
    IdleOrError: boolean;
    IIFKM: boolean;
    Inactive: boolean;
    IPR: boolean;
    KEI: boolean;
    Killed: boolean;
    Manual: boolean;
    Paused: boolean;
    PauseRequested: boolean;
    RecordingLogs: boolean;
    Resetting: boolean;
    RRI: boolean;
    Running: boolean;
    RunningOrStopping: boolean;
    State: number;
    StatusMsg: string;
    StepDescription: string;
    StepNum: number;
    Stopping: boolean;
}
export enum DeviceTypes {
    BASE = 0,
    AXIS = 1,
    BOSCHAXIS = 2,
    DUALAXIS = 3,
    GANTRY = 4,
    SYSTEM = 5,
    BRIDGE = 6,
    CONDUCTOR = 7,
    ROBOT = 8,
    EOAT = 9,
    VISION = 10,
    TWOPOS = 11,
    TWOPOSGANTRY = 12,
    EXTSERVICE = 13,
    HMI = 14,
}
export interface DeviceRegistration {
    ChildIdArray: Array<number>;
    DeviceType: DeviceTypes;
    Id: number;
    isExternalService: boolean;
    Mnemonic: string;
    ParentId: number;
}
export interface DeviceSettings {
    Bypass: boolean;
}
export interface UdpData {
    StreamVal: number;
}
export interface Device {
    ApiOpcua: ApiOpcuaData;
    Cfg: DeviceCfg;
    connectionStatus: boolean;
    Errors: DeviceFaultData;
    ExecMethod: ProcessData;
    instants: DeviceInstants;
    Is: DeviceSts;
    Mission: ProcessData;
    MutedChildrenArray: Array<boolean>;
    Process: ProcessData;
    Registration: DeviceRegistration;
    Script: ProcessData;
    Settings: DeviceSettings;
    SkipKillDuringAbortChildren: Array<boolean>;
    Task: ProcessData;
    Udp: UdpData;
    Warnings: DeviceFaultData;
}
export interface ComponentAnimation {
    AccentColor: number;
    BackgroundColor: number;
    FontColor: number;
    needsExpertUser: boolean;
    Visibility: number;
    wasClicked: boolean;
}
export interface HmiDevCtrlData {
    pbClear: ComponentAnimation;
    pbRelease: ComponentAnimation;
    pbReset: ComponentAnimation;
    pbStart: ComponentAnimation;
    pbStop: ComponentAnimation;
    pbTake: ComponentAnimation;
}
export interface HmiAxisCtrlData {
    pbBackAndForth: ComponentAnimation;
    pbHomeToTorque: ComponentAnimation;
    pbJogNeg: ComponentAnimation;
    pbJogPos: ComponentAnimation;
    pbMaster: ComponentAnimation;
    pbMoveToMax: ComponentAnimation;
    pbMoveToMin: ComponentAnimation;
    pbSetHardwareLimits: ComponentAnimation;
    pbSetRailBrakeEnforcement: ComponentAnimation;
    pbSetSoftwareLimits: ComponentAnimation;
    pbSetTorqueMode: ComponentAnimation;
    pbStop: ComponentAnimation;
    pbTorqueNeg: ComponentAnimation;
    pbTorquePos: ComponentAnimation;
    pbUnitTest: ComponentAnimation;
    pbVerifyNegSw: ComponentAnimation;
    pbVerifyPosSw: ComponentAnimation;
    radioBtnMotionProfile: number;
}
export interface ButtonBar {
    ClearFaultsBtn: ComponentAnimation;
    EnergizeBtn: ComponentAnimation;
    JobChangeBtn: ComponentAnimation;
    LoadBtn: ComponentAnimation;
    LockBtn: ComponentAnimation;
    ResetBtn: ComponentAnimation;
    ResetCncBtn: ComponentAnimation;
    StartBtn: ComponentAnimation;
    StopBtn: ComponentAnimation;
    UnloadBtn: ComponentAnimation;
    UnlockBtn: ComponentAnimation;
}
export type BYTE = number | string | unknown;
export interface HmiIbData {
    InductBtn: ComponentAnimation;
    requestControlBtn: ComponentAnimation;
    RetrieveAndStowBtn: ComponentAnimation;
    RetrieveBtn: ComponentAnimation;
    selectedCubbyId: number;
    selectedMissionId: number;
    StowBtn: ComponentAnimation;
    VendBtn: ComponentAnimation;
}
export interface StatusBar {
    BannerMode: number;
    BatchQty: number;
    CncTimeLeft: Date | string;
    DateAndTime: Date | string;
    FaultCodeData: FaultData;
    GoodCnt: number;
    JobName: string;
    PartNumber: string;
    Status: number;
    StatusMsg: number;
}
export interface HmiStwgData {
    DryCycleTestBtn: ComponentAnimation;
    InductBtn: ComponentAnimation;
    requestControlBtn: ComponentAnimation;
    RetrieveBtn: ComponentAnimation;
    StopBtn: ComponentAnimation;
    StowBtn: ComponentAnimation;
}
export interface HmiData {
    ActiveAxisSts: AxisSts;
    ActiveCodesysHmiScreenName: string;
    ActiveDev: Device;
    ActiveDevCtrl: HmiDevCtrlData;
    ActiveDeviceId: number;
    ActivePage: number;
    AxisCtrl: HmiAxisCtrlData;
    ButtonBar: ButtonBar;
    HeartbeatHMI: BYTE;
    HeartbeatPLC: BYTE;
    IB: HmiIbData;
    isConnected: boolean;
    RemoteControlPage: number;
    ScreenChangeBtn: ComponentAnimation;
    StatusBar: StatusBar;
    STWG: HmiStwgData;
}
export interface TwoPosInputs {
    SensA_ON: boolean;
    SensB_ON: boolean;
}
export interface AxisInputs {
    Brakes: RailBrakeInputs;
    Sensors: Array<boolean>;
}
export interface FixInputs {
    PartPresentSensors: Array<boolean>;
}
export interface PressureSwitchInputs {
    ActualPressure_PSI: number;
    AT_PRESSURE: boolean;
    TOO_HIGH: boolean;
}
export interface PotInputs {
    BallValve_CLOSED: boolean;
    BallValve_OPENED: boolean;
    PotPressureSw: PressureSwitchInputs;
}
export interface RobInputs {
    ApplicatorCalibrationSw_ON: boolean;
    ApplicatorTool_PRESENT: boolean;
    BrushTool_PRESENT: boolean;
    CameraTool_PRESENT: boolean;
    GripperTool_PRESENT: boolean;
}
export interface GuardLockInputs {
    LOCKED: boolean;
    RequestToEnterPb_ON: boolean;
    SafeInputs_OK: boolean;
    Solenoid_UNLOCKED: boolean;
    TONGUE_IN: boolean;
}
export interface SftyInputs {
    DoorSwitches_ALL_OK: boolean;
    EstopCircuit_OK: boolean;
    EstopCircuitDelayed_OK: boolean;
    EstopCircuitInputs_ALL_ON: boolean;
    EstopCircuitReset_READY: boolean;
    EstopInputs: Array<boolean>;
    EstopPbs_ALL_OK: boolean;
    FenceCircuit_OK: boolean;
    FenceCircuitInputs_ALL_ON: boolean;
    FenceCircuitReset_READY: boolean;
    FenceConditionForEstop_OK: boolean;
    GuardLocks: Array<GuardLockInputs>;
    Psc1AlarmCode: number;
    Psc1AlarmMsg: string;
    Psc1FatalErrorCode: number;
    Psc1FatalErrorMsg: string;
    Psc1StatusCode: number;
    Psc1StatusMsg: string;
    SafeContactorsNC_OK: boolean;
    SafeNC_ALL_OK: boolean;
    SafeValveNC_OK: boolean;
    UnlockGuardDoors_OUT: boolean;
}
export interface SysInputs {
    PowerSupplies_OK: Array<boolean>;
    PressureSwitches: Array<PressureSwitchInputs>;
}
export interface inputs_00251 {
    CLAMP_S: TwoPosInputs;
    CLAMP_T: TwoPosInputs;
    Dummy: AxisInputs;
    EOAT: TwoPosInputs;
    FIX_S: FixInputs;
    FIX_T: FixInputs;
    FLSB_S: TwoPosInputs;
    FLSB_T: TwoPosInputs;
    GRIP: TwoPosInputs;
    POT: PotInputs;
    ROB: RobInputs;
    SFTY: SftyInputs;
    SQUEE: AxisInputs;
    SYS: SysInputs;
}
export interface JobData {
    ActiveBatchNumber: number;
    ActiveRecipeIndex: number;
    AssemblyName: string;
    AssemblyNumber: string;
    BatchId: string;
    GoodCnt: number;
    JobCompleted: boolean;
    JobEndTime: string;
    JobName: string;
    JobStartTime: string;
    LotId: string;
    LotQty: number;
    OperationNumber: string;
    OperatorId: string;
    SalesOrderId: string;
    ScrapCnt: number;
    SetupCompleted: boolean;
    SetupEndTime: string;
    SetupStartTime: string;
    TubeTypeString: string;
    WorkInstruction: string;
    WorkOrderId: string;
}
export interface TwoPosOutputs {
    OutA: boolean;
    OutB: boolean;
}
export interface LiteOutputs {
    Green_ON: boolean;
    Red_ON: boolean;
    Yellow_ON: boolean;
}
export interface PotOutputs {
    BallValveOpen_REQ: boolean;
    PaintPot: TwoPosOutputs;
    PressureSetpoint_PSI: number;
}
export interface StrainGaugeInputs {
    CalbrationNextStepReq: boolean;
    CalibrateReq: boolean;
    ReferenceWeight_g: number;
    SampleReq: boolean;
    TareReq: boolean;
}
export interface RobOutputs {
    LoadCell: StrainGaugeInputs;
}
export interface GuardLockOutputs {
    RequestToEnterPb_FLASH: boolean;
    RequestToEnterPb_ILLUM: boolean;
    Unlock_REQ: boolean;
}
export interface SftyOutputs {
    ClearControllerAlarm_REQ: boolean;
    ControllerAlarm_CLEAR: boolean;
    EstopCircuit_RESET: boolean;
    EstopPbIllumns: Array<boolean>;
    GuardLocks: Array<GuardLockOutputs>;
    RequestToEnterPb_ON: boolean;
    ResetPb_FLASH: boolean;
    ResetPb_ILLUM: boolean;
    RobotTeachMode_ON: boolean;
}
export interface WeidmullerIoPwmOutput {
    ControlWord: number;
    PulseDuration: number;
}
export interface SysOutputs {
    StartPb_FLASH: boolean;
    StartPb_ILLUM: boolean;
}
export interface outputs_00251 {
    CLAMP_S: TwoPosOutputs;
    CLAMP_T: TwoPosOutputs;
    EOAT: TwoPosOutputs;
    FLSB_S: TwoPosOutputs;
    FLSB_T: TwoPosOutputs;
    GRIP: TwoPosOutputs;
    LITE: LiteOutputs;
    POT: PotOutputs;
    ROB: RobOutputs;
    SFTY: SftyOutputs;
    SQUEE: WeidmullerIoPwmOutput;
    SYS: SysOutputs;
}
export interface PartValidationData {
    LinerWeight_g: number;
    PostWeight_g: number;
    PreWeight_g: number;
    SerialNumber: string;
    StatusMsg: string;
    TimestampVision_sec: number;
    VisionSts: number;
    WeightSts: number;
}
export interface PartData {
    FixtureLocationWhenLoaded: number;
    InFixture: boolean;
    LoadedBadSensor: boolean;
    ProcessSts: number;
    Validation: PartValidationData;
}
export interface PartDataStatus {
    ActiveCnt: number;
    AllFixturesAreEmpty: boolean;
    AllStationsAreEmpty: boolean;
    BatchCntFlag: boolean;
    DoneShelfIsEmpty: boolean;
    DoneShelfIsFull: boolean;
    DoneShelfSpacesLeftCnt: number;
    FinishedCnt: number;
    OneOrMoreRejectPartsInCell: boolean;
    OneOrMoreRejectPartsInRobot: boolean;
    Parts: Array<PartData>;
    RawShelfIsEmpty: boolean;
    RawShelfPartsLeftCnt: number;
    RobotHasMachinedParts: boolean;
    RobotHasNoPostOpParts: boolean;
    RobotHasOneFinishedPart: boolean;
    RobotHasOnePreMachining: boolean;
    RobotHasOnePreTopDeburring: boolean;
    RobotHasOneRaw: boolean;
    RobotHasTwoPreMachining: boolean;
    RobotIsEmpty: boolean;
    ShortFixtureIsEmpty: boolean;
    TallFixtureIsEmpty: boolean;
}
export interface PotCfg {
    placeholder: boolean;
}
export interface PotSts {
    ActualPressure: number;
    AtTargetPressure: boolean;
    BallValve_CLOSED: boolean;
    BallValve_OPEN: boolean;
    Cfg: PotCfg;
    isDepressurized: boolean;
    isPressurizing: boolean;
    LinerIsFlowing: boolean;
    State: number;
    TargetPressure: number;
}
export interface RecipeStore {
    NumRecipes: number;
    Recipes: Array<RecipeData>;
}
export type RobCfg = unknown;
export interface StrainGaugeSts {
    CalibOffset: number;
    CalibScaleFactor: number;
    CurrentValue: number;
    RawValue: number;
    SampledStdDev: number;
    SampledValue: number;
    SampledValueRaw: number;
    State: number;
    StatusMsg: string;
    TareOffset: number;
    Unit: string;
}
export interface RobSts {
    ActiveToolDeviceId: number;
    ActiveToolId: number;
    ActualPosition: RobPositionData;
    ActualWaypoint: number;
    ActualZone: number;
    ActualZPositionRelativeToFalseBottom: number;
    AdjustedSetpoints: Array<ApplicatorSetpoint>;
    ApplicatorHasBeenPrimed: boolean;
    ApplicatorIsDirty: boolean;
    ApplyLinerStartSetpointMovesReq: boolean;
    AutoRecoveryNeeded: boolean;
    AutoRecoveryOk: boolean;
    CameraIsRecording: boolean;
    Cfg: RobCfg;
    GripperIsCalibrated: boolean;
    IController: AbbControllerInterface;
    LastCrossedApplyLinerSetpointId: number;
    LastRecordedLoadCellValue_g: number;
    LoadCellCurrentValue_g: number;
    LoadCellSts: StrainGaugeSts;
    SqueegeeCalibrationOffset: number;
    SqueegeeIsCalibrated: boolean;
    SqueegeeIsHomed: boolean;
    TargetWaypoint: number;
    VisionIsCalibrated: boolean;
    WeighTubeTareDone: boolean;
    WeighTubeWeighDone: boolean;
}
export interface SftyCfg {
    NumOfDoors: number;
}
export type SftySts = unknown;
export enum SM3ErrorSMCERROR {
    SMC_NO_ERROR = 0,
    SMC_DI_GENERAL_COMMUNICATION_ERROR = 1,
    SMC_DI_AXIS_ERROR = 2,
    SMC_DI_FIELDBUS_LOST_SYNCRONICITY = 3,
    SMC_DI_SWLIMITS_EXCEEDED = 10,
    SMC_DI_HWLIMITS_EXCEEDED = 11,
    SMC_DI_LINEAR_AXIS_OUTOFRANGE = 12,
    SMC_DI_HALT_OR_QUICKSTOP_NOT_SUPPORTED = 13,
    SMC_DI_VOLTAGE_DISABLED = 14,
    SMC_DI_IRREGULAR_ACTPOSITION = 15,
    SMC_DI_POSITIONLAGERROR = 16,
    SMC_DI_HOMING_ERROR = 17,
    SMC_DI_LICENSING_ERROR = 18,
    SMC_DI_DRIVE_LIMIT_ACTIVE = 19,
    SMC_REGULATOR_OR_START_NOT_SET = 20,
    SMC_WRONG_CONTROLLER_MODE = 21,
    SMC_INVALID_ACTION_FOR_LOGICAL = 25,
    SMC_AXIS_IS_NOT_OPERATIONAL = 27,
    SMC_FB_WASNT_CALLED_DURING_MOTION = 30,
    SMC_AXIS_IS_NO_AXIS_REF = 31,
    SMC_AXIS_REF_CHANGED_DURING_OPERATION = 32,
    SMC_FB_ACTIVE_AXIS_DISABLED = 33,
    SMC_AXIS_NOT_READY_FOR_MOTION = 34,
    SMC_AXIS_ERROR_DURING_MOTION = 35,
    SMC_FB_CALLED_FROM_WRONG_TASK = 36,
    SMC_VD_MAX_VELOCITY_EXCEEDED = 40,
    SMC_VD_MAX_ACCELERATION_EXCEEDED = 41,
    SMC_VD_MAX_DECELERATION_EXCEEDED = 42,
    SMC_3SH_INVALID_VELACC_VALUES = 50,
    SMC_3SH_MODE_NEEDS_HWLIMIT = 51,
    SMC_FRC_NO_FREE_HANDLE = 60,
    SMC_MAC_INITIALIZATION_FAILED = 65,
    SMC_MAC_INVALID_TASK_HANDLE = 66,
    SMC_MAC_TOO_MANY_TASKS = 67,
    SMC_MAC_ATOMIC_ADD_FAILED = 68,
    SMC_SDO_INVALID_DATALENGTH = 69,
    SMC_SCM_NOT_SUPPORTED = 70,
    SMC_SCM_AXIS_IN_WRONG_STATE = 71,
    SMC_SCM_INTERRUPTED = 72,
    SMC_ST_WRONG_CONTROLLER_MODE = 75,
    SMC_RAG_ERROR_DURING_STARTUP = 80,
    SMC_RAG_ERROR_AXIS_NOT_INITIALIZED = 81,
    SMC_PP_WRONG_AXIS_TYPE = 85,
    SMC_PP_NUMBER_OF_ABSOLUTE_BITS_INVALID = 86,
    SMC_NEGATIVE_MODULO_PERIOD = 87,
    SMC_CGR_ZERO_VALUES = 90,
    SMC_CGR_DRIVE_POWERED = 91,
    SMC_CGR_INVALID_POSPERIOD = 92,
    SMC_CGR_POSPERIOD_NOT_INTEGRAL = 93,
    SMC_FRACTION_TECH_UNITS_INVALID = 94,
    SMC_P_FTASKCYCLE_EMPTY = 110,
    SMC_R_NO_ERROR_TO_RESET = 120,
    SMC_R_DRIVE_DOESNT_ANSWER = 121,
    SMC_R_ERROR_NOT_RESETTABLE = 122,
    SMC_R_DRIVE_DOESNT_ANSWER_IN_TIME = 123,
    SMC_R_CANNOT_RESET_COMMUNICATION_ERROR = 124,
    SMC_RP_PARAM_UNKNOWN = 130,
    SMC_RP_REQUESTING_ERROR = 131,
    SMC_RP_DRIVE_PARAMETER_NOT_MAPPED = 132,
    SMC_RP_PARAM_CONVERSION_ERROR = 133,
    SMC_WP_PARAM_INVALID = 140,
    SMC_WP_SENDING_ERROR = 141,
    SMC_WP_DRIVE_PARAMETER_NOT_MAPPED = 142,
    SMC_WP_PARAM_CONVERSION_ERROR = 143,
    SMC_H_AXIS_WASNT_STANDSTILL = 170,
    SMC_H_AXIS_DIDNT_START_HOMING = 171,
    SMC_H_AXIS_DIDNT_ANSWER = 172,
    SMC_H_ERROR_WHEN_STOPPING = 173,
    SMC_H_AXIS_IN_ERRORSTOP = 174,
    SMC_MS_UNKNOWN_STOPPING_ERROR = 180,
    SMC_MS_INVALID_ACCDEC_VALUES = 181,
    SMC_MS_DIRECTION_NOT_APPLICABLE = 182,
    SMC_MS_AXIS_IN_ERRORSTOP = 183,
    SMC_BLOCKING_MC_STOP_WASNT_CALLED = 184,
    SMC_MS_AXIS_ALREADY_STOPPING = 185,
    SMC_UNKNOWN_TASK_INTERVAL = 200,
    SMC_MA_INVALID_VELACC_VALUES = 201,
    SMC_MA_INVALID_DIRECTION = 202,
    SMC_MR_INVALID_VELACC_VALUES = 226,
    SMC_MR_INVALID_DIRECTION = 227,
    SMC_OVR_INVALID_OVERRIDE_FACTORS = 231,
    SMC_MAD_INVALID_VELACC_VALUES = 251,
    SMC_MAD_INVALID_DIRECTION = 252,
    SMC_MSI_INVALID_VELACC_VALUES = 276,
    SMC_MSI_INVALID_DIRECTION = 277,
    SMC_MSI_INVALID_EXECUTION_ORDER = 278,
    SMC_LOGICAL_NO_REAL_AXIS = 300,
    SMC_MV_INVALID_ACCDEC_VALUES = 301,
    SMC_MV_DIRECTION_NOT_APPLICABLE = 302,
    SMC_PP_ARRAYSIZE = 325,
    SMC_PP_STEP0MS = 326,
    SMC_VP_ARRAYSIZE = 350,
    SMC_VP_STEP0MS = 351,
    SMC_AP_ARRAYSIZE = 375,
    SMC_AP_STEP0MS = 376,
    SMC_TP_TRIGGEROCCUPIED = 400,
    SMC_TP_COULDNT_SET_WINDOW = 401,
    SMC_TP_COMM_ERROR = 402,
    SMC_TRIGGER_OUT_OF_RANGE = 403,
    SMC_LATCH_IN_CONTROLLER_NOT_SUPPORTED = 404,
    SMC_AT_TRIGGERNOTOCCUPIED = 410,
    SMC_MCR_INVALID_VELACC_VALUES = 426,
    SMC_MCR_INVALID_DIRECTION = 427,
    SMC_MCA_INVALID_VELACC_VALUES = 451,
    SMC_MCA_INVALID_DIRECTION = 452,
    SMC_MCA_DIRECTION_NOT_APPLICABLE = 453,
    SMC_SDL_INVALID_AXIS_STATE = 475,
    SMC_SDL_INVALID_VELACC_VALUES = 476,
    SMC_SACF_INVALID_DYNAMIC_FACTOR = 480,
    SMC_CR_NO_TAPPETS_IN_CAM = 600,
    SMC_CR_TOO_MANY_TAPPETS = 601,
    SMC_CR_MORE_THAN_32_ACCESSES = 602,
    SMC_CI_NO_CAM_SELECTED = 625,
    SMC_CI_MASTER_OUT_OF_SCALE = 626,
    SMC_CI_RAMPIN_NEEDS_VELACC_VALUES = 627,
    SMC_CI_SCALING_INCORRECT = 628,
    SMC_CI_TOO_MANY_TAPPETS_PER_CYCLE = 629,
    SMC_CI_MORE_THAN_32_ACCESSES = 630,
    SMC_CB_NOT_IMPLEMENTED = 640,
    SMC_GI_RATIO_DENOM = 675,
    SMC_GI_INVALID_ACC = 676,
    SMC_GI_INVALID_DEC = 677,
    SMC_GI_MASTER_REGULATOR_CHANGED = 678,
    SMC_GI_INVALID_JERK = 679,
    SMC_PH_INVALID_VELACCDEC = 725,
    SMC_PH_ROTARYAXIS_PERIOD0 = 726,
    SMC_NO_CAM_REF_TYPE = 750,
    SMC_CAM_TABLE_DOES_NOT_COVER_MASTER_SCALE = 751,
    SMC_CAM_TABLE_EMPTY_MASTER_RANGE = 752,
    SMC_CAM_TABLE_INVALID_MASTER_MINMAX = 753,
    SMC_CAM_TABLE_INVALID_SLAVE_MINMAX = 754,
    SMC_CAM_INVALID_ELEMENT_COUNT = 755,
    SMC_GIP_MASTER_DIRECTION_CHANGE = 775,
    SMC_GIP_SLAVE_REVERSAL_CANNOT_BE_AVOIDED = 776,
    SMC_GIP_AVOID_REVERSAL_FOR_FINITE_AXIS = 777,
    SMC_GIP_MASTERSTARTDISTANCE_MUST_BE_ZERO_BUFFERED = 778,
    SMC_GIP_CANNOT_START_SYNC = 779,
    SMC_BC_BL_TOO_BIG = 800,
    SMC_QPROF_DIVERGES = 825,
    SMC_QPROF_INVALID_PARAMETER = 826,
    SMC_QPROF_NO_RESULT = 827,
    SMC_QPROF_INVALID_NEW_LBD = 828,
    SMC_QPROF_BAD_NEGOTIATION = 829,
    SMC_QPROF_INVALID_INTERVAL = 830,
    SMC_QPROF_NOT_ENOUGH_PHASES = 831,
    SMC_TG_INTERNAL_ERROR = 832,
    SMC_SRT_NOT_STANDSTILL_OR_POWEROFF = 850,
    SMC_SRT_INVALID_RAMPTYPE = 851,
    SMC_SMT_NOT_STANDSTILL_OR_POWEROFF = 852,
    SMC_SMT_INVALID_MOVEMENTTYPE_OR_POSITIONPERIOD = 853,
    SMC_SMT_AXIS_NOT_VIRTUAL = 854,
    SMC_NO_LICENSE = 1000,
    SMC_INT_VEL_ZERO = 1001,
    SMC_INT_NO_STOP_AT_END = 1002,
    SMC_INT_DATA_UNDERRUN = 1003,
    SMC_INT_VEL_NONZERO_AT_STOP = 1004,
    SMC_INT_TOO_MANY_RECURSIONS = 1005,
    SMC_INT_NO_CHECKVELOCITIES = 1006,
    SMC_INT_PATH_EXCEEDED = 1007,
    SMC_INT_VEL_ACC_DEC_ZERO = 1008,
    SMC_INT_DWIPOTIME_ZERO = 1009,
    SMC_INT_JERK_NONPOSITIVE = 1010,
    SMC_INT_QPROF_DIVERGES = 1011,
    SMC_INT_INVLALID_VELOCITY_MODE = 1012,
    SMC_INT_TOO_MANY_AXES_INTERPOLATED = 1013,
    SMC_INT_DEGENERATE_SEGMENT = 1014,
    SMC_HIGH_CURVATURE_SPLINE = 1015,
    SMC_INT2DIR_BUFFER_TOO_SMALL = 1050,
    SMC_INT2DIR_PATH_FITS_NOT_IN_QUEUE = 1051,
    SMC_XINT_INVALID_DIRECTION = 1070,
    SMC_XINT_NOINTERSECTION = 1071,
    SMC_WAR_INT_OUTQUEUE_TOO_SMALL = 1080,
    SMC_WAR_END_VELOCITIES_INCORRECT = 1081,
    SMC_CV_ACC_DEC_VEL_NONPOSITIVE = 1100,
    SMC_CA_INVALID_ACCDEC_VALUES = 1120,
    SMC_TOK_INCOMPLETE_TOKEN_AT_END_OF_INPUT = 1130,
    SMC_TOK_NOT_A_VALID_TOKEN = 1131,
    SMC_TOK_AMBIGUOUS_INPUT = 1132,
    SMC_TOK_STRING_TOO_LONG_FOR_TOKEN = 1133,
    SMC_TOK_INVALID_NUMLIT = 1134,
    SMC_PRS_FUNC_DECL_TOO_FEW_ARGUMENTS = 1150,
    SMC_PRS_FUNC_DECL_TOO_MANY_ARGUMENTS = 1151,
    SMC_PRS_FUNC_DECL_WRONG_ARGUMENT_TYPE = 1152,
    SMC_PRS_LOCAL_VAR_NOT_FOUND = 1153,
    SMC_PRS_INVALID_STRING = 1154,
    SMC_PRS_TOO_MANY_CLOSING_BRACKETS = 1155,
    SMC_PRS_TOO_MANY_OPENING_BRACKETS = 1156,
    SMC_PRS_NO_SUCH_INFIX_OPERATOR = 1157,
    SMC_PRS_NO_SUCH_PREFIX_OPERATOR = 1158,
    SMC_PRS_OPERATOR_INVALID_PRECEDENCE = 1159,
    SMC_PRS_NOT_A_TERM = 1160,
    SMC_PRS_EXPRESSION_INVALID_SEQUENCE = 1161,
    SMC_PRS_TOO_MANY_TERMS = 1162,
    SMC_PRS_STACK_OVERFLOW = 1163,
    SMC_PRS_VAR_NAME_ALREADY_USED = 1164,
    SMC_PRS_INCOMPLETE_SENTENCE_IN_TOKEN_QUEUE = 1165,
    SMC_PRS_TOO_MANY_SUBPROGRAMS = 1167,
    SMC_PRS_TOO_MANY_SUBPROGRAM_PARAMETERS = 1168,
    SMC_PRS_SUBPROGRAM_LOOKUP_FAILED = 1169,
    SMC_PRS_VAR_NOT_FOUND = 1170,
    SMC_PRS_TOKEN_TYPE_UNKNOWN = 1171,
    SMC_PRS_GOT_NO_TERM = 1172,
    SMC_PRS_INVALID_VAR_TYPE = 1173,
    SMC_PRS_UNEXPECTED_TOKEN = 1174,
    SMC_PRS_ID3_EXPECTED = 1175,
    SMC_PRS_ID_TOO_LONG = 1176,
    SMC_PRS_GADDRESS_EXPECTED = 1177,
    SMC_PRS_NWORD_EXPECTED = 1178,
    SMC_PRS_NWORD_INVALID_SENTENCE_NUMBER = 1179,
    SMC_PRS_NWORD_SENTENCE_NUMBER_NO_NUMBER_LITERAL = 1180,
    SMC_PRS_USE_OF_RESERVED_KEYWORD = 1181,
    SMC_PRS_SUBPROGRAMS_SIGNATURE_MISMATCH = 1182,
    SMC_PRS_INITIAL_VALUE_HAS_WRONG_TYPE = 1183,
    SMC_PRS_TOO_MANY_LOCAL_VARIABLES = 1184,
    SMC_PRS_SUBPROG_MUST_BE_FIRST_SENTENCE = 1185,
    SMC_PRS_ONLY_ONE_SUBPROGRAM_PER_FILE_ALLOWED = 1186,
    SMC_PRS_LET_AFTER_REGULAR_SENTENCE = 1187,
    SMC_PRS_UNMATCHED_END_SUBPROGRAM = 1188,
    SMC_PRS_UNEXPECTED_TOKENS_AFTER_SUBPROGRAM = 1189,
    SMC_PRS_MISSING_END_SUBPROGRAM = 1190,
    SMC_PRS_USE_OF_KEYWORD = 1191,
    SMC_PRS_DYNCALL_EXPECTED_SUBNAME_EXP = 1192,
    SMC_PRS_DYNCALL_EXPECTED_SUBNAME_TYPE_STRING = 1193,
    SMC_DEC_ACC_TOO_LITTLE = 1200,
    SMC_DEC_RET_TOO_LITTLE = 1201,
    SMC_DEC_OUTQUEUE_RAN_EMPTY = 1202,
    SMC_DEC_JUMP_TO_UNKNOWN_LINE = 1203,
    SMC_DEC_INVALID_SYNTAX = 1204,
    SMC_DEC_3DMODE_OBJECT_NOT_SUPPORTED = 1205,
    SMC_DEC_NEGATIVE_PERIOD = 1206,
    SMC_DEC_DIMENSIONS_EXCLUSIVE_AU = 1207,
    SMC_DEC_DIMENSIONS_EXCLUSIVE_BV = 1208,
    SMC_DEC_DIMENSIONS_EXCLUSIVE_CW = 1209,
    SMC_DEC_DCS_NOT_ALL_OF_ABC_GIVEN = 1210,
    SMC_DEC_DCS_2D_NOT_IN_XY_PLANE = 1211,
    SMC_DEC_CIRCLE_NON_UNIFORM_SCALING = 1212,
    SMC_DEC_ROTATION_AFFECTS_SCALING = 1213,
    SMC_DEC_DCS_NOT_ALL_OF_IJK_GIVEN = 1214,
    SMC_IPR_LOCAL_VAR_UNKNOWN_TYPE = 1250,
    SMC_IPR_LVALUE_WRONG_TYPE = 1251,
    SMC_IPR_EVAL_STACK_OVERFLOW = 1252,
    SMC_IPR_NOT_A_NUMBER = 1253,
    SMC_IPR_DIVISION_BY_ZERO = 1254,
    SMC_IPR_INVALID_SCALING_FACTORS = 1255,
    SMC_IPR_INTERPRETER_STACK_IMBALANCE = 1256,
    SMC_IPR_INTERPRETER_STACK_OVERFLOW = 1257,
    SMC_IPR_INVALID_INTERPRETER_STACK_BUFFER = 1258,
    SMC_IPR_BUFFER_TOO_SMALL = 1259,
    SMC_DNCCS_NO_DATA = 1280,
    SMC_DNCCS_TOO_MANY_CALLSTACKS = 1281,
    SMC_DNCCS_INVALID_PROGRAM_INDEX = 1282,
    SMC_DNCCS_TOO_MANY_PROGRAMS = 1283,
    SMC_DNCCS_WRONG_TASK = 1284,
    SMC_GCV_BUFFER_TOO_SMALL = 1300,
    SMC_GCV_BUFFER_WRONG_TYPE = 1301,
    SMC_GCV_UNKNOWN_IPO_LINE = 1302,
    SMC_CNC_INTERNAL_ERROR = 1400,
    SMC_PATH_MAX_HPOINTS_EXCEEDED = 1401,
    SMC_TRC_G75_NOT_ALLOWED = 1410,
    SMC_TRC_QUEUE_FULL_NON_CARTESIAN = 1411,
    SMC_TRC_SPLINE3D_5_NOT_SUPPORTED = 1412,
    SMC_TRC_PLANE_CHANGE_NOT_ALLOWED = 1414,
    SMC_CNC_INVALID_GEOINFO = 1415,
    SMC_CNC_CANNOT_APPEND_TO_OUTQUEUE = 1416,
    SMC_NAV_MAX_SUBPROGRAM_NESTING_EXCEEDED = 1450,
    SMC_NAV_RETURN_FROM_MAIN = 1451,
    SMC_NAV_SUBPROGRAM_DECLARATION_NOT_FOUND = 1452,
    SMC_NAV_NOT_ENOUGH_SPACE_FOR_COMPLETE_SENTENCE = 1453,
    SMC_NO_CNC_REF_TYPE = 1500,
    SMC_NO_OUTQUEUE_TYPE = 1501,
    SMC_GEOINFO_BUFFER_MISALIGNED = 1502,
    SMC_3D_MODE_NOT_SUPPORTED = 1600,
    SMC_SAA_SMOOTHAREA_TOO_LARGE = 1700,
    SMC_SAA_SP_INVALID_INPUT = 1701,
    SMC_SA_QUEUE_NOT_IN_BUFFER = 1800,
    SMC_SA_QUEUE_CHANGED_DURING_OP = 1801,
    SMC_OS_INVALID_PARAMETER = 1820,
    SMC_BSSP_IPO_NOT_ACTIVE = 1830,
    SMC_BS_SAVEDPOS_NOT_REACHED = 1831,
    SMC_BS_NO_POS_STORED = 1832,
    SMC_INVALID_FEATURE_FLAG = 1900,
    SMC_SMB_HFUN_NOT_SUPPORTED = 1901,
    SMC_SMB_ONLY_3DMODE = 1902,
    SMC_SMB_ERROR_COMPUTING_SPLINE = 1903,
    SMC_SMM_INVALID_PARAM_NUMBER = 1910,
    SMC_INVALID_PARAMETER = 1950,
    SMC_BLENDING_NOT_SUPPORTED_BY_PREVIOUS_MOVEMENT = 1951,
    SMC_BUFFERED_NOT_SUPPORTED_BY_PREVIOUS_MOVEMENT = 1952,
    SMC_INHERIT_OWNER_ACTIVE_MOVEMENT_NOT_CALLED = 1953,
    SMC_MOVING_WITHOUT_ACTIVE_MOVEMENT = 1954,
    SMC_BUFFER_MODE_NOT_SUPPORTED = 1955,
    SMC_ERROR_IN_A_PREVIOUS_MOVEMENT = 1956,
    SMC_MORE_THAN_ONE_MOVEMENT_PER_INSTANCE = 1957,
    SMC_RNCF_FILE_DOESNT_EXIST = 2000,
    SMC_RNCF_NO_BUFFER = 2001,
    SMC_RNCF_BUFFER_TOO_SMALL = 2002,
    SMC_RNCF_DATA_UNDERRUN = 2003,
    SMC_RNCF_VAR_COULDNT_BE_REPLACED = 2004,
    SMC_RNCF_NOT_VARLIST = 2005,
    SMC_RNCF_NO_STRINGBUFFER = 2006,
    SMC_RNCF_STRINGBUFFER_OVERRUN = 2007,
    SMC_RNCF_SUBPROGRAM_FILE_NOT_FOUND = 2008,
    SMC_RNCF_FILE_CANNOT_DETERMINE_SIZE = 2009,
    SMC_RNCQ_FILE_DOESNT_EXIST = 2050,
    SMC_RNCQ_NO_BUFFER = 2051,
    SMC_RNCQ_BUFFER_TOO_SMALL = 2052,
    SMC_RNCQ_UNEXPECTED_EOF = 2053,
    SMC_ADL_FILE_CANNOT_BE_OPENED = 2100,
    SMC_ADL_BUFFER_OVERRUN = 2101,
    SMC_RCAM_FILE_DOESNT_EXIST = 2200,
    SMC_RCAM_TOO_MUCH_DATA = 2201,
    SMC_RCAM_WRONG_COMPILE_TYPE = 2202,
    SMC_RCAM_WRONG_VERSION = 2203,
    SMC_RCAM_UNEXPECTED_EOF = 2204,
    SMC_WDPF_CHANNEL_OCCUPIED = 3001,
    SMC_WDPF_CANNOT_CREATE_FILE = 3002,
    SMC_WDPF_ERROR_WHEN_READING_PARAMS = 3003,
    SMC_WDPF_TIMEOUT_PREPARING_LIST = 3004,
    SMC_ENC_DENOM_ZERO = 5000,
    SMC_ENC_AXISUSEDBYOTHERFB = 5001,
    SMC_ENC_FILTER_DEPTH_INVALID = 5002,
    SMC_INTERNAL_ERROR_INIT_MOVEMENT = 6000,
    SMC_INVALID_AXIS_TYPE = 6001,
    SMC_PCCQ_POINTBUFFERTOOSMALL = 10000,
    SMC_PCCQ_INPUTBUFFERFULLBUTNOTFINALIZED = 10001,
    SMC_AXIS_GROUP_WRONG_STATE = 11000,
    SMC_AXIS_GROUP_TOO_MANY_AXES = 11001,
    SMC_AXIS_GROUP_INVALID_DYNLIMITS = 11002,
    SMC_AXIS_GROUP_INVALID_COORD_SYSTEM = 11004,
    SMC_AXIS_GROUP_SINGLE_AXIS_ERROR = 11005,
    SMC_MOVE_INVALID_BUFFER_MODE = 11006,
    SMC_MOVE_INVALID_DYNAMIC_FACTOR = 11007,
    SMC_MOVE_INVALID_DYNAMICS = 11008,
    SMC_AXIS_GROUP_AXIS_NOT_PART_OF_GROUP = 11009,
    SMC_AXIS_GROUP_NOT_SUPPORTED = 11010,
    SMC_AXIS_GROUP_KINEMATICS_NOT_SET = 11011,
    SMC_AXIS_GROUP_WRONG_NUMBER_OF_AXES = 11012,
    SMC_AXIS_GROUP_INTERRUPTED_BY_SINGLE_AXIS = 11013,
    SMC_AXIS_GROUP_FOLLOW_SETVALUES = 11014,
    SMC_AXIS_GROUP_TOO_MANY_DEPENDENCIES = 11015,
    SMC_AXIS_GROUP_MUTUAL_DEPENDENCY = 11016,
    SMC_AXIS_GROUP_DEPENDENCY_IN_DIFFERENT_TASK = 11017,
    SMC_AXIS_GROUP_AXIS_IN_DIFFERENT_TASK = 11018,
    SMC_AXIS_GROUP_PCS_STILL_IN_USE = 11019,
    SMC_AXIS_GROUP_CMD_ABORTED_DUE_TO_ERROR = 11020,
    SMC_AXIS_GROUP_INVALID_PARAMETER = 11021,
    SMC_AXIS_GROUP_UNSUPPORTED_RAMPTYPE = 11022,
    SMC_MOVE_INVALID_TRANSITION_PARAMETER = 11023,
    SMC_AXIS_GROUP_CPTR_CANNOT_FOLLOW = 11025,
    SMC_AXIS_GROUP_CONTINUE_WRONG_POSITION = 11026,
    SMC_AXIS_GROUP_CONTINUE_BUFFER_TOO_SMALL = 11027,
    SMC_AXIS_GROUP_CONTINUE_WRONG_CHECKSUM = 11028,
    SMC_AXIS_GROUP_IDLE_WAIT_AXES_MOVING = 11029,
    SMC_AXIS_INVERSE_TRAFO_EXCEEDING_POSLIMITS = 11030,
    SMC_AXIS_GROUP_CANNOT_ADD_SAME_AXIS = 11031,
    SMC_AXIS_GROUP_TRANSFORMATION_NOT_SET = 11032,
    SMC_AXIS_GROUP_NON_RESUMABLE_ERROR = 11033,
    SMC_AXIS_GROUP_CONTINUE_DATA_NOT_WRITTEN = 11034,
    SMC_AXIS_GROUP_INVALID_INTERRUPT_POSITION = 11036,
    SMC_RELATIVE_MOVEMENT_TRACKING_CS = 11037,
    SMC_RELATIVE_MOVEMENT_ABORTING_TRACKING = 11038,
    SMC_CIRCULAR_MOVEMENT_TRACKING_CS = 11039,
    SMC_CIRCULAR_MOVEMENT_ABORTING_TRACKING_CS = 11040,
    SMC_AXIS_GROUP_CONTINUE_POSITION_WRONG_CHECKSUM = 11041,
    SMC_CIRCULAR_TRACKING_TOOL_CHANGE_NOT_SUPPORTED = 11042,
    SMC_AXIS_GROUP_COULD_NOT_WRITE_CONTINUE_DATA = 11043,
    SMC_MODULO_AXIS_FOR_NON_ROTARY_JOINT = 11044,
    SMC_MODULO_AXIS_FOR_LIMITED_ROTARY_JOINT = 11045,
    SMC_MODULO_AXIS_PERIOD_NOT_360 = 11046,
    SMC_FB_WASNT_CALLED_DURING_EXECUTION = 11047,
    SMC_NO_EVALUATION_POSSIBLE_FOR_TIME_OFFSET = 11048,
    SMC_INVALID_SOURCE_TYPE_FOR_TIME_OFFSET = 11049,
    SMC_INVALID_TIME_OFFSET = 11050,
    SMC_TIME_OFFSET_TOO_LARGE = 11051,
    SMC_KERNEL_PTP_INTERNAL_ERROR = 11100,
    SMC_KERNEL_PTP_INVALID_TASKCYCLETIME = 11101,
    SMC_TRAFO_INVALID_PARAMETERS = 12000,
    SMC_TRAFO_INVALID_CONSTELLATION = 12001,
    SMC_TRAFO_INVALID_COUPLING = 12002,
    SMC_TRAFO_NOT_INITIALIZED = 12003,
    SMC_TRAFO_NO_TOOL_WITH_OFFSET_ALLOWED = 12004,
    SMC_AXIS_GROUP_TOOL_OFFSET_INCOMPATIBLE_WITH_KINEMATICS = 12005,
    SMC_TRAFO_INVALID_AXIS_LIMITS = 12006,
    SMC_AXIS_GROUP_PATH_DEVIATION_TOO_HIGH = 12007,
    SMC_AXIS_POSITION_EXCEEDS_POSLIMITS = 12008,
    SMC_AXIS_GROUP_NO_DYNAMIC_MODEL_CONFIGURED = 12009,
    SMC_DYNAMICS_NUM_TORQUES_NEQ_NUM_AXES = 12010,
    SMC_CP_CACHE_FULL = 12100,
    SMC_CP_EVAL_ERROR = 12101,
    SMC_CP_NON_CONTINUABLE_STATE = 12102,
    SMC_CP_MAX_LENGTH_EXCEEDED = 12103,
    SMC_CP_ACCELERATION_TOO_HIGH = 12104,
    SMC_CP_MAX_ITERATIONS_EXCEEDED = 12105,
    SMC_CP_NO_TRAJECTORY = 12106,
    SMC_CP_OUT_QUEUE_FULL = 12107,
    SMC_CP_QUEUE_UNDERRUN = 12108,
    SMC_CP_INVALID_QUEUE = 12109,
    SMC_CP_BLENDING_INTERNAL_ERROR = 12110,
    SMC_CP_CIRCLE_COLLINEAR_POINTS = 12111,
    SMC_CP_CIRCLE_CENTER_NOT_ON_BISECTOR = 12112,
    SMC_CP_CIRCLE_RADIUS_ZERO = 12113,
    SMC_CP_CIRCLE_DISTANCE_LARGER_THAN_DIAMETER = 12114,
    SMC_CP_CIRCLE_START_AND_ENDPOINT_EQUAL = 12115,
    SMC_CP_BLENDING_DEGENERATE_SPLINE = 12116,
    SMC_CP_ELEMENT_TOO_SHORT = 12117,
    SMC_CP_COULD_NOT_CUT_PATH = 12118,
    SMC_CP_INVALID_ANGULAR_VEL_ACC = 12119,
    SMC_CP_INVALID_ORIENTATION = 12120,
    SMC_CP_TIME_BUDGET_EXCEEDED = 12121,
    SMC_AXIS_GROUP_AXIS_LIMIT_VIOLATED = 12122,
    SMC_CP_CONFIGS_DIFFER = 12125,
    SMC_CP_BUS_TASK_NOT_CALLED = 12126,
    SMC_CP_NO_ROOT_IN_INTERVAL_FOUND = 12127,
    SMC_CP_KIN_DOES_NOT_SUPPORT_AXIS_ORIENTATION_IPO = 12128,
    SMC_CP_AXIS_ORIENTATION_IPO_NOT_SUPPORTED_FOR_CPTR = 12129,
    SMC_CP_INVALID_PATH_ELEM = 12130,
    SMC_CP_TRANSITION_NOT_SMOOTH = 12131,
    SMC_CP_AXIS_ORIENTATION_IPO_CONFIG_DIFFERS = 12132,
    SMC_CP_AXIS_ORIENTATION_IPO_OFFSET2_NOT_IMPLEMENTED = 12133,
    SMC_CP_ROTARY_AXIS_PERIOD_MISMATCH = 12134,
    SMC_CP_ROTARY_AXIS_RANGE_VIOLATION = 12135,
    SMC_CP_COMPUTE_TARGET_DISCONTINUITY = 12136,
    SMC_CP_TRAJECTORY_NOT_SMOOTH = 12137,
    SMC_CP_ERROR_CREATING_PARAM_TRANSFORM = 12138,
    SMC_CP_PTP_DATA_NUMBER_OF_AXES = 12139,
    SMC_CP_NEGATIVE_PATH_VELOCITY = 12140,
    SMC_CP_TRANSITIONING_FROM_SINGLE_AXIS_MOVEMENT_NOT_SUPPORTED = 12141,
    SMC_CP_PLANNER_NO_PROGRESS = 12142,
    SMC_CP_INTERNAL_EVAL_CACHE_ERROR = 12143,
    SMC_CP_INVALID_ROOT_ACC_TOO_HIGH = 12144,
    SMC_CP_INVALID_ROOT_TRAJECTORY_TOO_LARGE = 12145,
    SMC_CP_EMPTY_TRAJECTORY = 12146,
    SMC_CP_FORECAST_TOO_LARGE = 12147,
    SMC_GROUPJOG2_MAX_DISTANCE_NON_POSITIVE = 12200,
    SMC_GROUPJOG2_DYNAMIC_CS_NOT_SUPPORTED = 12201,
    SMC_TRIGGER_TOO_MANY_TRIGGERS_PREPARED = 12300,
    SMC_TRIGGER_UNSUPPORTED_MOVEMENT_TYPE = 12301,
    SMC_TRIGGER_INVALID_POS_TYPE = 12302,
    SMC_TRIGGER_RELATIVE_POSITION_OUT_OF_RANGE = 12303,
    SMC_TRIGGER_PLANE_NORMAL_NOT_A_UNIT = 12304,
    SMC_TRIGGER_PLANE_DISTANCE_NEGATIVE = 12305,
    SMC_TRIGGER_PLANE_COORD_SYSTEM_INVALID = 12306,
    SMC_TRIGGER_DISTANCE_OUT_OF_RANGE = 12307,
    SMC_TRIGGER_PLANE_NO_INTERSECTION = 12308,
    SMC_TRIGGER_TRACKING_TRANSITION_NOT_SUPPORTED = 12309,
    SMC_TRIGGER_PTP_NOT_SUPPORTED = 12310,
    SMC_FIRST_INTERNAL_ERROR_CODE = 13000,
    SMC_MOVEMENT_INTERNAL_ERROR = 13001,
    SMC_MOVEMENT_GET_POS_INTERNAL_ERROR = 13002,
    SMC_CPTR_INTERNAL_ERROR = 13003,
    SMC_CP_IPO_INTERNAL_ERROR = 13004,
    SMC_CP_ADD_NEW_MOVEMENT_INTERNAL_ERROR = 13005,
    SMC_AXIS_GROUP_COORDINATION_INTERNAL_ERROR = 13006,
    SMC_AXIS_GROUP_ADD_MOVEMENT_INTERNAL_ERROR = 13007,
    SMC_AXIS_GROUP_READ_AXIS_STATES_INTERNAL_ERROR = 13008,
    SMC_AXIS_GROUP_READ_VEL_INTERNAL_ERROR = 13009,
    SMC_AXIS_GROUP_READ_ACC_INTERNAL_ERROR = 13010,
    SMC_AXIS_GROUP_INVALID_STATE_INTERNAL_ERROR = 13011,
    SMC_AXIS_GROUP_PCS_INTERNAL_ERROR = 13012,
    SMC_AXIS_GROUP_INTERRUPT_INTERNAL_ERROR = 13013,
    SMC_CONTINUE_DATA_READ_INTERNAL_ERROR = 13014,
    SMC_CONTINUE_DATA_WRITE_INTERNAL_ERROR = 13015,
    SMC_PATH_ELEM_INTERNAL_ERROR = 13016,
    SMC_PATH_ELEM_ESTIMATE_LIMITS_INTERNAL_ERROR = 13017,
    SMC_PATH_ELEM_ZERO_LEN_INTERNAL_ERROR = 13018,
    SMC_PATH_ELEM_BLEND_INTERNAL_ERROR = 13019,
    SMC_PATH_ELEM_BLEND_GEO_INTERNAL_ERROR = 13020,
    SMC_PATH_ELEM_BLEND_ORI_INTERNAL_ERROR = 13021,
    SMC_PATH_ELEM_BLEND_AS_INTERNAL_ERROR = 13022,
    SMC_ELEM_FUN_CART_INTERNAL_ERROR = 13023,
    SMC_CP_HALT_STOP_INTERNAL_ERROR = 13024,
    SMC_TRJ_PLANNING_INIT_INTERNAL_ERROR = 13025,
    SMC_TRJ_PLANNING_GEN_SAMPLES_INTERNAL_ERROR = 13026,
    SMC_TRJ_PLANNING_PATH_OUT_INTERNAL_ERROR = 13027,
    SMC_TRJ_PLANNING_EVAL_AXIS_INTERNAL_ERROR = 13028,
    SMC_TRJ_PLANNING_LOOKAHEAD_INTERNAL_ERROR = 13029,
    SMC_AXIS_GROUP_READ_JERK_INTERNAL_ERROR = 13030,
    SMC_AXIS_GROUP_WRITE_CONTINUE_POS_INTERNAL_ERROR = 13031,
    SMC_CP_TRANSITION_CHECK_FAILED = 13032,
    SMC_ABORTING_INTERNAL_ERROR = 13033,
    SMC_LINE_TO_REL_STANDSTILL_INTERNAL_ERROR = 13034,
    SMC_PATH_ELEM_POSE_EVAL_INTERNAL_ERROR = 13035,
    SMC_CS_REF_COUNT_INTERNAL_ERROR = 13036,
    SMC_PATH_QUEUE_INTERNAL_ERROR = 13037,
    SMC_PATH_ELEM_QUEUE_INTERNAL_ERROR = 13038,
    SMC_ELEM_FUN_QUEUE_INTERNAL_ERROR = 13039,
    SMC_MAC_DUPLICATE_CALLER_INTERNAL_ERROR = 13040,
    SMC_MAC_INTERNAL_ERROR = 13041,
    SMC_READ_POSITION_INTERNAL_ERROR = 13042,
    SMC_ELEM_FUN_PROJECT_POINT_INTERNAL_ERROR = 13043,
    SMC_LAST_INTERNAL_ERROR_CODE = 13999,
}
export interface AxisSimpleSts {
    ActiveStreamType: number;
    actualAcceleration: number;
    ActualControllerMode: number;
    ActualCurrent: number;
    actualMasterAxisDevId: number;
    actualPosition: number;
    ActualTorque: number;
    actualVelocity: number;
    atHomePosition: boolean;
    atOperationalPositionMax: boolean;
    atOperationalPositionMin: boolean;
    AxesPositionDifference_CORRECTABLE: boolean;
    AxesPositionDifference_OK: boolean;
    CalculatedStoppingPosition: number;
    Cfg: AxisCfg;
    ConfiguredSoftLimitTravelRange: number;
    DriveHasError: boolean;
    DriveHwLimitsEnforcement: AxisLimitEnforcements;
    DriveIsStoppingMotor: boolean;
    DriveState: number;
    DriveStatusMsg: string;
    DriveStoppedMotor: boolean;
    DriveSwLimitsEnforcement: AxisLimitEnforcements;
    DualAxisStopType: DualAxisStopTypes;
    EtherCatComms_OK: boolean;
    HomeOffsetFromZero: number;
    ignoringRailBrakes: boolean;
    Interlocks: AxisInterlocks;
    isAtPosAndStandstill: boolean;
    isEnabled: boolean;
    isGeared: boolean;
    isHomed: boolean;
    isHoming: boolean;
    isJogging: boolean;
    isMastered: boolean;
    isMoving: boolean;
    isStandstill: boolean;
    isStreaming: boolean;
    isTorquing: boolean;
    mutingSwAndHwLimitsWhileHoming: boolean;
    Permissives: Array<AxisPermissiveStsData>;
    PositionDifference: number;
    RailBrakes: RailBrakeInputs;
    RcControlMode: enumRcAxisMode;
    RcHomingState: enumRcAxisHomingState;
    RecordedPosition: number;
    RestrictedToSlow: boolean;
    Sensors: Array<boolean>;
    setAccel: number;
    setJerk: number;
    setPosition: number;
    setTorque: number;
    setVelocity: number;
    SkippingPositionCorrectionBeforeGearing: boolean;
    SoftMotionErrorId: SM3ErrorSMCERROR;
    SoftMotionHasError: boolean;
    TargetControllerMode: number;
    targetDir: number;
    targetEncoderSetpoint: number;
    targetMasterAxisDevId: number;
    targetMaxCurrent: number;
    targetMotionProfileData: AxisMotionProfileData;
    targetMotionProfileId: number;
    targetPosition: number;
    targetSetpoint: number;
    targetTorque: number;
    targetVelocity: number;
    TravelLimitNegative: number;
    TravelLimitPositive: number;
}
export interface TaskData {
    description: string;
    paramArray: Array<number>;
    state: number;
    targetId: number;
    taskId: number;
}
export interface TaskQueue {
    activeTaskIndex: number;
    taskCnt: number;
    taskList: Array<TaskData>;
    topPriority: number;
}
export interface UdpInterfaceCfg {
    Last3DigitsOfIpcIpAddr: number;
    ListenPort: number;
    TargetIpAddress: string;
    TargetPort: number;
}
export interface UdpCfg {
    DeviceIdArray: Array<number>;
    HeartbeatTimeoutSec: number;
    udpStatusDataSchemaVersion: number;
    UpdInterfaceCfg: UdpInterfaceCfg;
}
export interface UdpSts {
    IncomingDataIsRecent: boolean;
    UdpPeerIsRunning: boolean;
}
export interface ExtServiceCfg {
    triggerErrorIfLostHeartbeat: boolean;
}
export interface CameraStatus {
    isConnected: boolean;
    isPluggedIn: boolean;
    isStreaming: boolean;
    recordingState: number;
    videoDeviceNodeString: string;
}
export interface CameraCfg {
    id: number;
    serialNumber: string;
    streamingPort: number;
}
export interface VisCfg {
    autoConnect: boolean;
    autoStream: boolean;
    cameraCfgs: Array<CameraCfg>;
    numCameras: number;
}
export interface IExtServiceInputs {
    ActiveTaskId: number;
    ErrorId: number;
    flipBit: boolean;
    heartbeatVal: number;
    lastTaskId: number;
    StepNum: number;
    TaskStepNum: number;
    UniqueTaskActiveId: number;
}
export interface IExtServiceOutputs {
    deviceCmdReqId: number;
    ExecMethodReqId: number;
    heartbeatVal: number;
    TaskParam0: number;
    TaskParam1: number;
    TaskParam2: number;
    TaskParam3: number;
    TaskReqId: number;
    UniqueTaskReqId: number;
}
export interface IExtService {
    i: IExtServiceInputs;
    o: IExtServiceOutputs;
}
export interface VisSts {
    allDisconnected: boolean;
    CameraStates: Array<CameraStatus>;
    Cfg: VisCfg;
    ExtServiceCfg: ExtServiceCfg;
    IExtService: IExtService;
    isConnected: boolean;
    isRecording: boolean;
    PluggedInSerialNumbers: Array<string>;
}

export type Machine_00251 = {
    AbbCfg: RctrlCfg;
    AbbHmiManual: RctrlHmiManual;
    AbbSts: RctrlSts;
    ActiveRecipe: RecipeData;
    Clamp_sCfg: TwoPosCfg;
    clamp_sSts: TwoPosSts;
    Clamp_tCfg: TwoPosCfg;
    clamp_tSts: TwoPosSts;
    EoatCfg: TwoPosCfg;
    EoatSts: TwoPosSts;
    Fix_sCfg: TwoPosGantryCfg;
    Fix_sSts: TwoPosGantrySts;
    Fix_tCfg: TwoPosGantryCfg;
    Fix_tSts: TwoPosGantrySts;
    Flsb_sCfg: TwoPosCfg;
    Flsb_sSts: TwoPosSts;
    Flsb_tCfg: TwoPosCfg;
    Flsb_tSts: TwoPosSts;
    GripCfg: TwoPosCfg;
    GripSts: TwoPosSts;
    HmiCfg: HmiCfg;
    HmiSts: HmiData;
    inputs: inputs_00251;
    Job: JobData;
    outputs: outputs_00251;
    PdmSts: PartDataStatus;
    PotCfg: PotCfg;
    PotSts: PotSts;
    RecipeStore: RecipeStore;
    RobCfg: RobCfg;
    RobSts: RobSts;
    SftyCfg: SftyCfg;
    SftySts: SftySts;
    SqueeCfg: AxisCfg;
    SqueeSts: AxisSimpleSts;
    TaskQueue: TaskQueue;
    UdpCfg: UdpCfg;
    UdpSts: UdpSts;
    VisCfg: ExtServiceCfg;
    VisSts: VisSts;
    VisStsExtService: VisSts;
};
export type MachineTypeRoot = {
    AbbCfg: RctrlCfg;
    AbbHmiManual: RctrlHmiManual;
    AbbSts: RctrlSts;
    ActiveRecipe: RecipeData;
    Clamp_sCfg: TwoPosCfg;
    clamp_sSts: TwoPosSts;
    Clamp_tCfg: TwoPosCfg;
    clamp_tSts: TwoPosSts;
    EoatCfg: TwoPosCfg;
    EoatSts: TwoPosSts;
    Fix_sCfg: TwoPosGantryCfg;
    Fix_sSts: TwoPosGantrySts;
    Fix_tCfg: TwoPosGantryCfg;
    Fix_tSts: TwoPosGantrySts;
    Flsb_sCfg: TwoPosCfg;
    Flsb_sSts: TwoPosSts;
    Flsb_tCfg: TwoPosCfg;
    Flsb_tSts: TwoPosSts;
    GripCfg: TwoPosCfg;
    GripSts: TwoPosSts;
    HmiCfg: HmiCfg;
    HmiSts: HmiData;
    inputs: inputs_00251;
    Job: JobData;
    outputs: outputs_00251;
    PdmSts: PartDataStatus;
    PotCfg: PotCfg;
    PotSts: PotSts;
    RecipeStore: RecipeStore;
    RobCfg: RobCfg;
    RobSts: RobSts;
    SftyCfg: SftyCfg;
    SftySts: SftySts;
    SqueeCfg: AxisCfg;
    SqueeSts: AxisSimpleSts;
    TaskQueue: TaskQueue;
    UdpCfg: UdpCfg;
    UdpSts: UdpSts;
    VisCfg: ExtServiceCfg;
    VisSts: VisSts;
    VisStsExtService: VisSts;
};
export type Machine_00251RuntimeExcludedKeys = 'SyncClockReq' | 'ResetEthercat_REQ' | 'DeviceLogs' | 'RegisteredInputs' | 'Utilities' | 'RegisteredDevices' | 'Devices' | 'DeviceRegisteredActions' | 'SysFb';
export type Machine_00251Runtime = Omit<Machine_00251, Machine_00251RuntimeExcludedKeys>;
export type MachineRuntimeRoot = Omit<MachineTypeRoot, Machine_00251RuntimeExcludedKeys>;
