// This file is generated by machine-bridge/src/type-generator/generate-machine-types.ts
// It captures the browsed Machine tag structure for later bridge-side iteration.
// Do not edit by hand; rerun the generator against a live OPC UA server.

export interface MachineTagNode {
    tag: string;
    children?: Record<string, MachineTagNode>;
    items?: readonly MachineTagNode[];
}

export const machineTagSource = {
    "controllerName": "CODESYS Control for Linux SL",
    "endpoint": "opc.tcp://127.0.0.1:4840",
    "rootNodeId": "ns=4;s=|var|CODESYS Control for Linux SL.Application.Machine_0251",
    "rootTag": "Machine_0251"
} as const;

export const machineTags: MachineTagNode = {
    tag: "Machine_0251",
};

export function* iterateMachineTags(node: MachineTagNode = machineTags): Generator<string> {
    yield node.tag;

    if (node.children) {
        for (const child of Object.values(node.children)) {
            yield* iterateMachineTags(child);
        }
    }

    if (node.items) {
        for (const child of node.items) {
            yield* iterateMachineTags(child);
        }
    }
}

export function collectMachineTags(node: MachineTagNode = machineTags): string[] {
    return Array.from(iterateMachineTags(node));
}
