// This file is generated by machine-bridge/src/type-generator/generate-machine-types.ts
// Output location defaults to machine-bridge/generated-types/shared/types.ts.
// Do not edit by hand; rerun the generator against a live OPC UA server.

export const machineTypeSource = {
    "controllerName": "CODESYS Control for Linux SL",
    "endpoint": "opc.tcp://127.0.0.1:4840",
    "generatedAt": "2026-05-29T19:56:40.386Z",
    "rootNodeId": "ns=4;s=|var|CODESYS Control for Linux SL.Application.Machine_0251",
    "rootTag": "Machine_0251"
} as const;


export type Machine_0251 = unknown;
export type MachineTypeRoot = unknown;
export type Machine_0251RuntimeExcludedKeys = 'SyncClockReq' | 'ResetEthercat_REQ' | 'DeviceLogs' | 'RegisteredInputs' | 'Utilities' | 'RegisteredDevices' | 'Devices' | 'DeviceRegisteredActions' | 'SysFb';
export type Machine_0251Runtime = Omit<Machine_0251, Machine_0251RuntimeExcludedKeys>;
export type MachineRuntimeRoot = Omit<MachineTypeRoot, Machine_0251RuntimeExcludedKeys>;
